-- Examples stay disabled until the owning gameplay resource is installed,
-- configured in permissions.lua, and explicitly enabled here.
NoirIllegal.Activities = {
    drug_sale = {
        enabled = true,
        callers = { 'noir_illegal_core' },
        cooldownSeconds = 0,
        idempotencyTtlSeconds = 2592000,
        personal = { drug = 2, street = 1 },
        organization = { drug = 1 },
        heat = 0.35,
        diminishingReturns = {
            windowSeconds = 3600,
            softCap = 20,
            floorMultiplier = 0.20,
            curve = 'linear',
            key = 'player:activity',
        },
        requirements = {},
        metadata = { allow = { 'zoneId', 'saleType', 'targetId' } },
    },
    outpost_claim = {
        enabled = true,
        callers = { 'noir_outposts' },
        cooldownSeconds = 0,
        idempotencyTtlSeconds = 2592000,
        personal = { street = 2 },
        organization = { street = 5 },
        heat = 2.0,
        requirements = { organization = true },
        metadata = { allow = { 'outpostId', 'previousOwnerId' } },
    },
    outpost_sale = {
        enabled = true,
        callers = { 'noir_outposts' },
        cooldownSeconds = 0,
        idempotencyTtlSeconds = 2592000,
        personal = { drug = 0 },
        organization = { drug = 1 },
        heat = 0,
        diminishingReturns = {
            windowSeconds = 3600,
            softCap = 30,
            floorMultiplier = 0.20,
            curve = 'linear',
            key = 'organization:activity',
        },
        requirements = { organization = true },
        metadata = { allow = { 'outpostId', 'dealerId', 'product', 'quantity' } },
    },
    outpost_robbery = {
        enabled = true,
        callers = { 'noir_outposts' },
        cooldownSeconds = 900,
        idempotencyTtlSeconds = 2592000,
        personal = { street = 2 },
        organization = {},
        heat = 4.0,
        requirements = {},
        metadata = { allow = { 'outpostId', 'dealerId', 'lootValue' } },
    },
}
