const EMOJI_KEYWORDS: Record<string, string> = {
    '😀': 'grin happy smile face', '😃': 'happy smile face', '😄': 'happy laugh smile',
    '😁': 'grin beam happy', '😆': 'laugh haha', '🤣': 'rofl rolling laugh funny',
    '😂': 'joy tears laugh cry funny', '🙂': 'slight smile', '😊': 'blush smile happy',
    '😇': 'angel innocent halo', '🥰': 'love hearts smiling', '😍': 'heart eyes love',
    '🤩': 'star struck wow', '😘': 'kiss blow', '😗': 'kiss', '😚': 'kiss', '😙': 'kiss',
    '😋': 'yum tasty tongue', '😛': 'tongue', '😜': 'wink tongue', '🤪': 'zany crazy goofy',
    '😝': 'tongue', '🤑': 'money mouth rich', '🤗': 'hug', '🤭': 'giggle oops',
    '🤫': 'shush quiet silent', '🤔': 'thinking hmm', '🤐': 'zipper mouth quiet',
    '🤨': 'raised eyebrow suspicious', '😐': 'neutral meh', '😑': 'expressionless',
    '😶': 'no mouth speechless', '😏': 'smirk', '😒': 'unamused meh', '🙄': 'eye roll',
    '😬': 'grimace awkward', '🤥': 'lying liar', '😔': 'pensive sad', '😪': 'sleepy tired',
    '🤤': 'drool', '😴': 'sleep zzz tired', '😷': 'mask sick', '🤒': 'sick thermometer ill',
    '🤕': 'hurt bandage injured', '🤢': 'nausea sick gross', '🤮': 'vomit puke sick',
    '🤧': 'sneeze sick', '🥵': 'hot heat sweating', '🥶': 'cold freezing', '🥴': 'woozy drunk',
    '😵': 'dizzy ko', '🤯': 'mind blown shocked', '🤠': 'cowboy', '🥳': 'party celebrate',
    '😎': 'cool sunglasses', '🤓': 'nerd geek glasses', '😕': 'confused', '😟': 'worried',
    '🙁': 'frown sad', '☹️': 'frown sad', '😮': 'surprised oh wow', '😲': 'astonished shocked',
    '😳': 'flushed embarrassed', '🥺': 'pleading puppy beg', '😦': 'frown', '😧': 'anguished',
    '😨': 'fearful scared', '😰': 'anxious sweat', '😥': 'sad disappointed', '😢': 'cry sad tear',
    '😭': 'sob cry bawl', '😱': 'scream fear shock', '😖': 'confounded', '😣': 'persevere',
    '😞': 'disappointed sad', '😓': 'sweat', '😩': 'weary tired', '😫': 'tired exhausted',
    '🥱': 'yawn bored tired', '😤': 'huff angry steam', '😡': 'angry mad rage red',
    '😠': 'angry mad', '🤬': 'swear curse angry', '😈': 'devil evil grin', '👿': 'devil angry imp',
    '💀': 'skull death dead', '☠️': 'skull death poison', '💩': 'poop crap', '🤡': 'clown',
    '👹': 'ogre monster', '👺': 'goblin', '👻': 'ghost boo halloween', '👽': 'alien ufo',
    '👾': 'alien game invader', '🤖': 'robot bot',
    '👋': 'wave hi bye hello', '🤚': 'hand raised', '🖐': 'hand fingers', '✋': 'hand stop high five',
    '🖖': 'vulcan spock', '👌': 'ok perfect', '🤌': 'pinch italian', '🤏': 'pinch small tiny',
    '✌️': 'peace victory', '🤞': 'fingers crossed luck hope', '🤟': 'love you', '🤘': 'rock horns metal',
    '🤙': 'call shaka hang loose', '👈': 'left point', '👉': 'right point', '👆': 'up point',
    '🖕': 'middle finger', '👇': 'down point', '☝️': 'up point one', '👍': 'thumbs up like yes good',
    '👎': 'thumbs down dislike no bad', '✊': 'fist raised', '👊': 'fist punch bump', '🤛': 'fist left',
    '🤜': 'fist right', '👏': 'clap applause bravo', '🙌': 'raise hands praise hooray', '🫶': 'heart hands love',
    '👐': 'open hands', '🤲': 'palms up', '🙏': 'pray thanks please hope', '✍️': 'writing pen',
    '💅': 'nails polish', '🤳': 'selfie', '💪': 'muscle strong flex gym', '🦾': 'mechanical arm',
    '🦿': 'mechanical leg', '🦵': 'leg', '🦶': 'foot', '👂': 'ear', '🦻': 'ear hearing',
    '👃': 'nose', '🫀': 'heart organ anatomical', '🫁': 'lungs', '🧠': 'brain', '🦷': 'tooth',
    '🦴': 'bone', '👁': 'eye', '👅': 'tongue', '👄': 'mouth lips', '🫦': 'lips bite',
    '🐶': 'dog puppy', '🐱': 'cat kitten', '🐭': 'mouse', '🐹': 'hamster', '🐰': 'rabbit bunny',
    '🦊': 'fox', '🐻': 'bear', '🐼': 'panda', '🐨': 'koala', '🐯': 'tiger', '🦁': 'lion',
    '🐮': 'cow', '🐷': 'pig', '🐸': 'frog', '🐵': 'monkey', '🙈': 'monkey see no evil',
    '🙉': 'monkey hear no evil', '🙊': 'monkey speak no evil', '🐔': 'chicken hen', '🐧': 'penguin',
    '🐦': 'bird', '🐤': 'chick baby', '🦆': 'duck', '🦅': 'eagle', '🦉': 'owl', '🦇': 'bat',
    '🐺': 'wolf', '🐗': 'boar', '🐴': 'horse', '🦄': 'unicorn', '🐝': 'bee honey', '🐛': 'bug caterpillar',
    '🦋': 'butterfly', '🐌': 'snail slow', '🐞': 'ladybug', '🐜': 'ant', '🕷': 'spider',
    '🐢': 'turtle tortoise', '🐍': 'snake', '🦎': 'lizard', '🐙': 'octopus', '🦑': 'squid',
    '🦐': 'shrimp', '🦀': 'crab', '🐡': 'pufferfish', '🐠': 'fish tropical', '🐟': 'fish',
    '🐬': 'dolphin', '🐳': 'whale', '🐋': 'whale', '🦈': 'shark', '🐊': 'crocodile alligator',
    '🐘': 'elephant', '🦛': 'hippo', '🦏': 'rhino', '🦒': 'giraffe', '🦘': 'kangaroo',
    '🦬': 'bison', '🐃': 'buffalo', '🐂': 'ox', '🐄': 'cow', '🐎': 'horse racing', '🐖': 'pig',
    '🐏': 'ram', '🐑': 'sheep', '🦙': 'llama alpaca', '🐐': 'goat', '🦌': 'deer', '🐕': 'dog',
    '🐩': 'poodle dog', '🐈': 'cat', '🌵': 'cactus', '🌲': 'evergreen tree pine', '🌳': 'tree',
    '🌴': 'palm tree', '🌱': 'seedling sprout plant', '🌿': 'herb plant leaves', '☘️': 'shamrock clover',
    '🍀': 'four leaf clover luck', '🍃': 'leaf wind', '🍂': 'fallen leaves autumn', '🍁': 'maple leaf',
    '🍄': 'mushroom', '🌾': 'wheat rice grain', '💐': 'bouquet flowers', '🌷': 'tulip flower',
    '🌹': 'rose flower', '🥀': 'wilted flower', '🌺': 'hibiscus flower', '🌸': 'cherry blossom flower',
    '🌼': 'daisy flower', '🌻': 'sunflower', '🌞': 'sun face', '🌝': 'full moon face', '🌛': 'moon',
    '🌜': 'moon', '🌚': 'new moon dark face', '🌕': 'full moon', '🌙': 'crescent moon night',
    '⭐': 'star', '🌟': 'star glowing sparkle', '☁️': 'cloud', '⛅': 'sun cloud partly',
    '🌈': 'rainbow', '🔥': 'fire flame lit hot', '💧': 'water drop droplet', '🌊': 'wave ocean water sea',
    '❄️': 'snow snowflake cold', '⚡': 'lightning bolt thunder', '🌪': 'tornado', '🌫': 'fog mist',
    '🍏': 'green apple', '🍎': 'red apple', '🍐': 'pear', '🍊': 'orange tangerine', '🍋': 'lemon',
    '🍌': 'banana', '🍉': 'watermelon', '🍇': 'grapes', '🍓': 'strawberry', '🫐': 'blueberry',
    '🍈': 'melon', '🍒': 'cherries', '🍑': 'peach', '🥭': 'mango', '🍍': 'pineapple', '🥥': 'coconut',
    '🥝': 'kiwi', '🍅': 'tomato', '🍆': 'eggplant', '🥑': 'avocado', '🥦': 'broccoli',
    '🥬': 'lettuce greens', '🥒': 'cucumber', '🌶': 'chili pepper spicy hot', '🌽': 'corn',
    '🥕': 'carrot', '🧄': 'garlic', '🧅': 'onion', '🥔': 'potato', '🍠': 'sweet potato yam',
    '🥐': 'croissant', '🥯': 'bagel', '🍞': 'bread', '🥖': 'baguette bread', '🧀': 'cheese',
    '🥚': 'egg', '🍳': 'fried egg breakfast', '🧈': 'butter', '🥞': 'pancakes', '🧇': 'waffle',
    '🥓': 'bacon', '🥩': 'steak meat', '🍗': 'chicken drumstick leg', '🍖': 'meat bone',
    '🌭': 'hot dog', '🍔': 'burger hamburger', '🍟': 'fries chips', '🍕': 'pizza', '🌮': 'taco',
    '🌯': 'burrito wrap', '🥗': 'salad', '🥘': 'paella pan', '🍝': 'pasta spaghetti', '🍜': 'ramen noodles',
    '🍲': 'stew soup pot', '🍛': 'curry rice', '🍣': 'sushi', '🍱': 'bento box', '🥟': 'dumpling',
    '🍤': 'fried shrimp tempura', '🍙': 'rice ball onigiri', '🍚': 'rice', '🍘': 'rice cracker',
    '🥮': 'mooncake', '🧁': 'cupcake', '🍰': 'cake slice shortcake', '🎂': 'birthday cake',
    '🍮': 'pudding flan custard', '🍭': 'lollipop candy', '🍬': 'candy sweet', '🍫': 'chocolate',
    '🍿': 'popcorn', '🍩': 'donut doughnut', '🍪': 'cookie', '🌰': 'chestnut', '🥜': 'peanut nuts',
    '🧃': 'juice box', '🥤': 'soda drink cup', '🧋': 'boba bubble tea', '☕': 'coffee tea hot',
    '🍵': 'tea green', '🫖': 'teapot', '🍺': 'beer', '🍻': 'beers cheers', '🥂': 'champagne cheers toast',
    '🍷': 'wine', '🥃': 'whiskey liquor', '🍸': 'cocktail martini', '🍹': 'cocktail tropical drink',
    '🍾': 'champagne bottle pop',
    '🚗': 'car auto', '🚕': 'taxi cab', '🚙': 'suv car', '🚌': 'bus', '🚎': 'trolleybus',
    '🏎': 'race car fast', '🚓': 'police car', '🚑': 'ambulance', '🚒': 'fire truck',
    '🚐': 'minibus van', '🛻': 'pickup truck', '🚚': 'delivery truck', '🚛': 'truck lorry',
    '🚜': 'tractor farm', '🛵': 'scooter moped', '🏍': 'motorcycle bike', '🚲': 'bicycle bike',
    '🛴': 'kick scooter', '🛹': 'skateboard', '⚓': 'anchor', '⛵': 'sailboat', '🚤': 'speedboat',
    '🛥': 'motor boat', '🛳': 'passenger ship', '🚢': 'ship', '✈️': 'airplane plane flight',
    '🛩': 'small plane', '🚁': 'helicopter', '🚀': 'rocket launch space', '🛸': 'ufo flying saucer',
    '🌍': 'earth globe europe africa world', '🌎': 'earth globe americas world', '🌏': 'earth globe asia world',
    '🗺': 'map world', '🧭': 'compass', '🏔': 'snow mountain', '⛰': 'mountain', '🌋': 'volcano',
    '🗻': 'mount fuji', '🏕': 'camping tent', '🏖': 'beach umbrella', '🏗': 'construction crane',
    '🏘': 'houses neighborhood', '🏠': 'house home', '🏡': 'house garden home', '🏢': 'office building',
    '🏥': 'hospital', '🏦': 'bank', '🏨': 'hotel', '🏩': 'love hotel', '🏪': 'convenience store',
    '🏫': 'school', '🏬': 'department store', '🏭': 'factory', '🏯': 'japanese castle', '🏰': 'castle',
    '💒': 'wedding chapel', '🗼': 'tokyo tower', '🗽': 'statue of liberty', '⛪': 'church',
    '🕌': 'mosque', '⛺': 'tent', '🎠': 'carousel merry go round', '🎡': 'ferris wheel',
    '🎢': 'roller coaster', '💈': 'barber pole', '🎪': 'circus tent',
    '⌚': 'watch time', '📱': 'phone mobile cell', '💻': 'laptop computer', '🖥': 'desktop computer monitor',
    '🖨': 'printer', '🖱': 'mouse computer', '💾': 'floppy disk save', '💿': 'cd disk', '📀': 'dvd disk',
    '📷': 'camera photo', '📸': 'camera flash photo', '📹': 'video camera', '🎥': 'movie camera film',
    '📞': 'phone receiver call', '☎️': 'telephone', '📺': 'tv television', '📻': 'radio', '🔋': 'battery',
    '🔌': 'plug electric', '💡': 'light bulb idea', '🔦': 'flashlight torch', '🕯': 'candle',
    '💰': 'money bag', '💵': 'dollar money cash bill', '💳': 'credit card', '🪙': 'coin',
    '💎': 'diamond gem jewel', '⚖️': 'scales justice balance', '🔧': 'wrench tool', '🔨': 'hammer tool',
    '🛠': 'tools hammer wrench', '🔩': 'nut bolt screw', '🔪': 'knife cut', '🔬': 'microscope science',
    '🔭': 'telescope space', '💊': 'pill medicine drug', '💉': 'syringe shot vaccine needle',
    '🩹': 'bandage plaster', '🎒': 'backpack bag school', '👜': 'handbag purse', '👛': 'purse coin',
    '🎩': 'top hat', '👒': 'hat sun', '👟': 'sneaker shoe running', '👠': 'high heel shoe',
    '👡': 'sandal', '👢': 'boot', '🥾': 'hiking boot', '💄': 'lipstick makeup', '💍': 'ring engagement diamond',
    '🔑': 'key', '🗝': 'old key', '🔐': 'lock key secure', '🔒': 'lock closed', '🔓': 'unlock open',
    '🔏': 'lock pen', '🚪': 'door', '🪑': 'chair seat', '🛋': 'couch sofa', '🪞': 'mirror',
    '🛁': 'bathtub bath', '🚿': 'shower', '🧹': 'broom sweep clean', '🧺': 'basket laundry',
    '🧻': 'toilet paper roll', '🚽': 'toilet', '🪠': 'plunger', '🧼': 'soap', '🫧': 'bubbles',
    '🪤': 'mouse trap', '🧲': 'magnet', '🪜': 'ladder', '🧰': 'toolbox', '⚗️': 'alembic chemistry',
    '📡': 'satellite antenna dish', '💣': 'bomb', '🧨': 'firecracker dynamite', '🎆': 'fireworks',
    '🎇': 'sparkler firework', '🧸': 'teddy bear toy', '🪆': 'nesting doll matryoshka', '🎈': 'balloon',
    '🎀': 'ribbon bow', '🎁': 'gift present wrapped', '🎊': 'confetti ball party', '🎉': 'party popper tada celebrate',
    '🎎': 'japanese dolls', '🎏': 'carp streamer flags', '🎐': 'wind chime', '🧧': 'red envelope money',
    '🎑': 'moon viewing ceremony', '🎃': 'pumpkin jack lantern halloween', '🎄': 'christmas tree xmas',
    '🎋': 'tanabata tree', '🎍': 'pine decoration bamboo',
    '⚽': 'soccer football ball', '🏀': 'basketball', '🏈': 'american football', '⚾': 'baseball',
    '🥎': 'softball', '🎾': 'tennis', '🏐': 'volleyball', '🏉': 'rugby', '🥏': 'frisbee disc',
    '🎱': 'pool billiards 8 ball', '🪀': 'yoyo', '🏓': 'ping pong table tennis', '🏸': 'badminton',
    '🏒': 'ice hockey', '🥍': 'lacrosse', '🏏': 'cricket', '🪃': 'boomerang', '🥅': 'goal net',
    '⛳': 'golf flag', '🪁': 'kite', '🏹': 'bow arrow archery', '🎣': 'fishing rod', '🤿': 'diving mask',
    '🥊': 'boxing glove', '🥋': 'martial arts karate', '🎽': 'running shirt', '🛷': 'sled',
    '⛸': 'ice skate', '🥌': 'curling stone', '🎿': 'skis', '⛷': 'skier', '🏂': 'snowboard',
    '🪂': 'parachute skydive', '🏋': 'weight lifting gym workout', '🤼': 'wrestling', '🤸': 'cartwheel gymnastics',
    '⛹': 'basketball player', '🤺': 'fencing', '🤾': 'handball', '🏌': 'golfer golf', '🏇': 'horse racing jockey',
    '🧘': 'yoga meditation zen', '🏄': 'surfing surf', '🏊': 'swimming swim', '🤽': 'water polo',
    '🚣': 'rowing boat', '🧗': 'climbing', '🚵': 'mountain biking', '🚴': 'cycling bike',
    '🏆': 'trophy win champion', '🥇': 'gold medal first', '🥈': 'silver medal second', '🥉': 'bronze medal third',
    '🏅': 'medal', '🎖': 'military medal', '🎗': 'ribbon awareness', '🎫': 'ticket', '🎟': 'admission tickets',
    '🤹': 'juggling', '🎭': 'theater drama masks', '🩰': 'ballet shoes', '🎨': 'art palette painting',
    '🖼': 'framed picture art', '🎰': 'slot machine casino', '🎲': 'dice game', '🧩': 'puzzle piece jigsaw',
    '🃏': 'joker card', '🀄': 'mahjong', '🎴': 'flower cards', '🎮': 'game controller gaming video',
    '🕹': 'joystick arcade', '🎯': 'dart target bullseye',
    '❤️': 'red heart love', '🧡': 'orange heart', '💛': 'yellow heart', '💚': 'green heart',
    '💙': 'blue heart', '💜': 'purple heart', '🖤': 'black heart', '🤍': 'white heart', '🤎': 'brown heart',
    '💔': 'broken heart breakup', '❤️‍🔥': 'heart on fire burning love', '❤️‍🩹': 'mending heart healing',
    '💕': 'two hearts love', '💞': 'revolving hearts', '💓': 'beating heart', '💗': 'growing heart',
    '💖': 'sparkling heart', '💘': 'heart arrow cupid', '💝': 'heart with ribbon gift', '💟': 'heart decoration',
    '☮️': 'peace', '✝️': 'cross christian', '☪️': 'star crescent islam', '🕉': 'om hindu', '✡️': 'star of david jewish',
    '🔯': 'six pointed star', '🪯': 'khanda sikh', '☯️': 'yin yang', '🛐': 'place of worship',
    '♈': 'aries zodiac', '♉': 'taurus zodiac', '♊': 'gemini zodiac', '♋': 'cancer zodiac',
    '♌': 'leo zodiac', '♍': 'virgo zodiac', '♎': 'libra zodiac', '♏': 'scorpio zodiac',
    '♐': 'sagittarius zodiac', '♑': 'capricorn zodiac', '♒': 'aquarius zodiac', '♓': 'pisces zodiac',
    '⛎': 'ophiuchus zodiac', '🔀': 'shuffle', '🔁': 'repeat loop', '🔂': 'repeat one', '▶️': 'play',
    '⏩': 'fast forward', '⏭': 'next track skip', '⏯': 'play pause', '◀️': 'reverse play back',
    '⏪': 'rewind', '⏮': 'previous track', '🔼': 'up button', '⏫': 'fast up', '🔽': 'down button',
    '⏬': 'fast down', '⏸': 'pause', '⏹': 'stop', '⏺': 'record', '🎦': 'cinema',
    '🔅': 'dim low brightness', '🔆': 'bright high brightness', '📶': 'signal bars reception',
    '📳': 'vibration mode', '📴': 'phone off', '📵': 'no phones', '🔇': 'mute muted', '🔈': 'speaker low',
    '🔉': 'speaker medium volume', '🔊': 'speaker loud volume', '📢': 'loudspeaker announce', '📣': 'megaphone cheer',
    '🔔': 'bell notification', '🔕': 'bell off mute silent', '🎵': 'music note', '🎶': 'music notes',
    '⚠️': 'warning caution alert', '🚸': 'children crossing', '🔞': 'no one under 18 adult',
    '♻️': 'recycle recycling', '✅': 'check mark yes done correct', '❎': 'cross mark no', '🆗': 'ok',
    '🆙': 'up new', '🆕': 'new', '🆓': 'free', '🆒': 'cool', '🔱': 'trident', '🔰': 'beginner japanese',
    '💠': 'diamond shape', '♾': 'infinity forever', '🔴': 'red circle dot', '🟠': 'orange circle',
    '🟡': 'yellow circle', '🟢': 'green circle', '🔵': 'blue circle', '🟣': 'purple circle',
    '⚫': 'black circle', '⚪': 'white circle', '🟤': 'brown circle',
    '🏁': 'checkered flag race finish', '🚩': 'red flag triangle', '🎌': 'crossed flags japan',
    '🏴': 'black flag', '🏳': 'white flag surrender', '🏳️‍🌈': 'rainbow pride flag lgbt gay',
    '🏳️‍⚧️': 'transgender pride flag trans', '🏴‍☠️': 'pirate flag skull', '🇺🇸': 'usa america united states flag',
    '🇬🇧': 'uk united kingdom britain england flag', '🇨🇦': 'canada flag', '🇦🇺': 'australia flag',
    '🇩🇪': 'germany german flag', '🇫🇷': 'france french flag', '🇮🇹': 'italy italian flag',
    '🇪🇸': 'spain spanish flag', '🇵🇹': 'portugal flag', '🇧🇷': 'brazil flag', '🇲🇽': 'mexico flag',
    '🇳🇱': 'netherlands holland flag', '🇧🇪': 'belgium flag', '🇨🇭': 'switzerland swiss flag',
    '🇦🇹': 'austria flag', '🇵🇱': 'poland polish flag', '🇷🇺': 'russia russian flag', '🇺🇦': 'ukraine flag',
    '🇯🇵': 'japan japanese flag', '🇨🇳': 'china chinese flag', '🇰🇷': 'korea south korean flag',
    '🇮🇳': 'india indian flag', '🇸🇦': 'saudi arabia flag', '🇹🇷': 'turkey flag', '🇮🇱': 'israel flag',
    '🇿🇦': 'south africa flag', '🇳🇬': 'nigeria flag', '🇦🇷': 'argentina flag', '🇨🇱': 'chile flag',
    '🇨🇴': 'colombia flag', '🇵🇪': 'peru flag', '🇻🇪': 'venezuela flag', '🇸🇪': 'sweden swedish flag',
    '🇩🇰': 'denmark danish flag', '🇳🇴': 'norway flag', '🇫🇮': 'finland flag', '🇮🇸': 'iceland flag',
    '🇮🇪': 'ireland irish flag', '🇬🇷': 'greece greek flag', '🇨🇿': 'czech flag', '🇸🇰': 'slovakia flag',
    '🇭🇺': 'hungary flag', '🇷🇴': 'romania flag', '🇧🇬': 'bulgaria flag', '🇭🇷': 'croatia flag',
    '🇷🇸': 'serbia flag', '🇸🇮': 'slovenia flag', '🇱🇹': 'lithuania flag', '🇱🇻': 'latvia flag',
    '🇪🇪': 'estonia flag', '🇲🇹': 'malta flag', '🇨🇾': 'cyprus flag', '🇱🇺': 'luxembourg flag',
    '🇸🇬': 'singapore flag', '🇲🇾': 'malaysia flag', '🇮🇩': 'indonesia flag', '🇹🇭': 'thailand flag',
    '🇻🇳': 'vietnam flag', '🇵🇭': 'philippines flag', '🇵🇰': 'pakistan flag', '🇧🇩': 'bangladesh flag',
    '🇱🇰': 'sri lanka flag', '🇳🇵': 'nepal flag',
    '✨': 'sparkles shine glitter', '💯': 'hundred 100 score perfect', '👀': 'eyes looking look',
    '🫡': 'salute respect', '🤝': 'handshake deal agree',
    '🙃': 'upside down silly', '🫠': 'melting hot', '🥲': 'smiling tear happy cry',
    '🥹': 'holding back tears emotional grateful', '🫢': 'hand over mouth gasp oops',
    '🫣': 'peeking shy nervous', '🫥': 'dotted line invisible hide', '😮‍💨': 'exhale relief sigh',
    '😵‍💫': 'spiral dizzy confused', '😶‍🌫️': 'clouds face foggy', '🫨': 'shaking shocked',
    '🫰': 'finger heart love money', '🫵': 'point you', '🫱': 'rightward hand',
    '🫲': 'leftward hand', '🫳': 'palm down', '🫴': 'palm up',
    '🦮': 'guide dog service', '🐈‍⬛': 'black cat', '🪶': 'feather', '🦩': 'flamingo',
    '🦚': 'peacock', '🦜': 'parrot', '🦢': 'swan', '🦫': 'beaver', '🦦': 'otter',
    '🦥': 'sloth', '🦧': 'orangutan', '🦣': 'mammoth', '🦤': 'dodo bird', '🪱': 'worm',
    '🪰': 'fly', '🪲': 'beetle bug', '🪳': 'cockroach', '🦟': 'mosquito', '🦠': 'microbe germ virus',
    '🐉': 'dragon', '🦕': 'dinosaur sauropod', '🦖': 'trex dinosaur', '🪸': 'coral reef',
    '🪷': 'lotus flower', '🪴': 'potted plant', '🐾': 'paw prints',
    '🫛': 'pea pod', '🫚': 'ginger root', '🧆': 'falafel', '🫔': 'tamale', '🥫': 'canned food can',
    '🍢': 'oden skewer', '🍡': 'dango sweet', '🧊': 'ice cube', '🫙': 'jar', '🥠': 'fortune cookie',
    '🥡': 'takeout box', '🫓': 'flatbread', '🧂': 'salt', '🥨': 'pretzel', '🫕': 'fondue',
    '🍶': 'sake', '🧉': 'mate drink',
    '🛺': 'auto rickshaw tuktuk', '🚊': 'tram', '🚉': 'station', '🚆': 'train', '🚄': 'bullet train',
    '🚅': 'bullet train fast', '🚈': 'light rail', '🚝': 'monorail', '🚋': 'tram car',
    '🚂': 'locomotive steam train', '🛞': 'wheel', '🛟': 'ring buoy life', '⛽': 'fuel gas station',
    '🚏': 'bus stop', '🚦': 'traffic light', '🚥': 'traffic light horizontal', '🗿': 'moai statue',
    '🏟': 'stadium', '🏛': 'classical building museum', '⛲': 'fountain', '🌁': 'foggy',
    '🌃': 'night stars city', '🌆': 'cityscape dusk', '🌇': 'sunset city', '🌉': 'bridge night',
    '🏞': 'national park nature',
    '🛼': 'roller skate', '🪅': 'pinata party', '🪩': 'disco ball mirror', '🪈': 'flute',
    '🪕': 'banjo', '🎸': 'guitar', '🎹': 'piano keyboard', '🥁': 'drum', '🎺': 'trumpet',
    '🎷': 'saxophone', '🪗': 'accordion', '🎻': 'violin', '🪘': 'long drum', '♟': 'chess pawn',
    '🪫': 'low battery empty', '🧾': 'receipt', '🪪': 'id card license', '🛗': 'elevator lift',
    '🪮': 'hair pick comb', '🪥': 'toothbrush', '🧴': 'lotion bottle', '🧷': 'safety pin',
    '🧯': 'fire extinguisher', '🪦': 'headstone grave', '⚰️': 'coffin', '⚱️': 'urn ashes',
    '🪧': 'sign placard', '📿': 'prayer beads', '🧿': 'nazar evil eye', '🪬': 'hamsa hand',
    '🔮': 'crystal ball fortune', '🪄': 'magic wand', '🪛': 'screwdriver', '🪚': 'saw', '🪓': 'axe',
    '🛡': 'shield', '🗡': 'dagger knife', '🔫': 'water gun pistol', '🪣': 'bucket', '🧽': 'sponge',
    '🌡': 'thermometer', '🧪': 'test tube', '🧫': 'petri dish', '🧬': 'dna',
    '🩷': 'pink heart', '🩵': 'light blue heart', '🩶': 'grey heart gray', '➕': 'plus add',
    '➖': 'minus subtract', '➗': 'divide division', '✖️': 'multiply times x', '🟰': 'equals',
    '♥️': 'heart suit', '♠️': 'spade suit', '♣️': 'club suit', '♦️': 'diamond suit',
    '⛔': 'no entry forbidden', '🚫': 'prohibited no ban', '💢': 'anger symbol mad',
    '💥': 'collision boom explosion', '💫': 'dizzy stars', '💦': 'sweat droplets water',
    '💨': 'dash wind fast', '🕳': 'hole', '💬': 'speech bubble chat', '💭': 'thought bubble',
    '🗯': 'anger speech bubble', '♨️': 'hot springs', '✳️': 'eight spoked asterisk',
    '✴️': 'eight pointed star', '❇️': 'sparkle', '©️': 'copyright', '®️': 'registered',
    '™️': 'trademark', '🔟': 'ten keycap 10', '🆔': 'id', '🆘': 'sos help', '🆚': 'versus vs',
    '🇪🇺': 'european union eu flag', '🇳🇿': 'new zealand flag', '🇪🇬': 'egypt flag',
    '🇲🇦': 'morocco flag', '🇰🇪': 'kenya flag', '🇬🇭': 'ghana flag', '🇪🇹': 'ethiopia flag',
    '🇩🇿': 'algeria flag', '🇹🇳': 'tunisia flag', '🇶🇦': 'qatar flag', '🇦🇪': 'uae emirates flag',
    '🇰🇼': 'kuwait flag', '🇮🇶': 'iraq flag', '🇮🇷': 'iran flag',
    '🏴󠁧󠁢󠁥󠁮󠁧󠁿': 'england flag', '🏴󠁧󠁢󠁳󠁣󠁴󠁿': 'scotland flag', '🏴󠁧󠁢󠁷󠁬󠁳󠁿': 'wales flag',
};

const stripVS = (e: string): string => e.replace(/️/g, '');

const NORMALIZED: Record<string, string> = (() => {
    const out: Record<string, string> = {};
    for (const key in EMOJI_KEYWORDS) out[stripVS(key)] = EMOJI_KEYWORDS[key];
    return out;
})();

export function emojiKeywords(emoji: string): string {
    return NORMALIZED[stripVS(emoji)] ?? '';
}

export function emojiName(emoji: string): string {
    const kw = emojiKeywords(emoji);
    if (!kw) return '';
    const phrase = kw.split(' ').slice(0, 2).join(' ');
    return phrase.charAt(0).toUpperCase() + phrase.slice(1);
}
