ALTER TABLE noir_weed_plants ADD COLUMN IF NOT EXISTS care_sum FLOAT NOT NULL DEFAULT 0;
ALTER TABLE noir_weed_plants ADD COLUMN IF NOT EXISTS care_ticks INT UNSIGNED NOT NULL DEFAULT 0;
ALTER TABLE noir_weed_plants ADD COLUMN IF NOT EXISTS skill_level TINYINT UNSIGNED NOT NULL DEFAULT 1;
