CREATE TABLE IF NOT EXISTS `noir_graffiti` (
    `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    `graffiti_type` VARCHAR(16) NOT NULL DEFAULT 'text',
    `text_value` VARCHAR(64) NOT NULL,
    `font` VARCHAR(64) NOT NULL,
    `color` VARCHAR(16) NOT NULL,
    `gang_name` VARCHAR(64) NULL,
    `x` DOUBLE NOT NULL,
    `y` DOUBLE NOT NULL,
    `z` DOUBLE NOT NULL,
    `normal_x` FLOAT NOT NULL,
    `normal_y` FLOAT NOT NULL,
    `normal_z` FLOAT NOT NULL,
    `rotation` FLOAT NOT NULL DEFAULT 0,
    `scale` FLOAT NOT NULL DEFAULT 1,
    `territory_id` VARCHAR(64) NULL,
    `placed_by` VARCHAR(64) NOT NULL,
    `placed_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    `removed_by` VARCHAR(64) NULL,
    `removed_at` TIMESTAMP NULL,
    PRIMARY KEY (`id`),
    INDEX `idx_noir_graffiti_gang` (`gang_name`),
    INDEX `idx_noir_graffiti_territory` (`territory_id`),
    INDEX `idx_noir_graffiti_active` (`removed_at`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
