-- Custom add-on vehicle catalogue. Official GTA models and all resource
-- options remain in config.lua; this file only contributes custom spawn names.

if type(Config) ~= 'table' or type(Config.Vehicles) ~= 'table' then
    error('[drs_vehicleshop] config-addons.lua must be loaded after config.lua')
end

local addonVehicles = {
    ["compacts"] = {
        ["dilet"] = { name = "Dilettante Custom", brand = "Karin", model = "dilet", price = 40298, category = "compacts", image = "dilet.webp" },
        ["panto2"] = { name = "Panto 4", brand = "Benefactor", model = "panto2", price = 85000, category = "compacts" },
        ["quail"] = { name = "Quail", brand = "Dewbauchee", model = "quail", price = 85522, category = "compacts", image = "quail.webp" },
        ["zodiac"] = { name = "Zodiac", brand = "Vulcar", model = "zodiac", price = 37546, category = "compacts", image = "zodiac.webp" },
        ["zodiacc"] = { name = "Zodiac C", brand = "Vulcar", model = "zodiacc", price = 37546, category = "compacts", image = "zodiacc.webp" },
        ["zodiacr"] = { name = "Zodiac R", brand = "Vulcar", model = "zodiacr", price = 37546, category = "compacts", image = "zodiacr.webp" },
    },
    ["coupes"] = {
        ["gbsapphire"] = { name = "Sapphire", brand = "Enus", model = "gbsapphire", price = 100000, category = "coupes", image = "gbsapphire.webp" },
        ["gbsentinelgts"] = { name = "Sentinel GTS", brand = "Ubermacht", model = "gbsentinelgts", price = 100000, category = "coupes", image = "gbsentinelgts.webp" },
        ["vdingo1"] = { name = "Dingo", brand = "Cheval", model = "vdingo1", price = 65522, category = "coupes", image = "vdingo1.webp" },
        ["vdingo2"] = { name = "Dingo SS", brand = "Cheval", model = "vdingo2", price = 75522, category = "coupes", image = "vdingo2.webp" },
        ["vorstand"] = { name = "Vorstand", brand = "Ubermacht", model = "vorstand", price = 65522, category = "coupes", image = "vorstand.webp" },
    },
    ["sedans"] = {
        ["admiral"] = { name = "Admiral (1999)", brand = "Dundreary", model = "admiral", price = 10516, category = "sedans", image = "admiral.webp" },
        ["algoschafter"] = { name = "Schafter V12 LWB (2018)", brand = "Benefactor", model = "algoschafter", price = 165682, category = "sedans", image = "algoschafter.webp" },
        ["arabasterope2s"] = { name = "Asterope S (Arab)", brand = "Karin", model = "arabasterope2s", price = 71306, category = "sedans", image = "arabasterope2s.webp" },
        ["asterope2s"] = { name = "Asterope S", brand = "Karin", model = "asterope2s", price = 71306, category = "sedans", image = "asterope2s.webp" },
        ["cognoscentis"] = { name = "Cognoscenti Custom", brand = "Enus", model = "cognoscentis", price = 85522, category = "sedans", image = "cognoscentis.webp" },
        ["df8"] = { name = "DF8-90", brand = "Imponte", model = "df8", price = 64370, category = "sedans", image = "df8.webp" },
        ["eaglesedan"] = { name = "Eagle (2024)", brand = "Bravado", model = "eaglesedan", price = 62617, category = "sedans", image = "eaglesedan.webp" },
        ["elegant"] = { name = "Elegant (1999)", brand = "Willard", model = "elegant", price = 20339, category = "sedans", image = "elegant.webp" },
        ["gbadmiral"] = { name = "Admiral (2009)", brand = "Dundreary", model = "gbadmiral", price = 50000, category = "sedans", image = "gbadmiral.webp" },
        ["gbargento7f"] = { name = "Argento 7F", brand = "Obey", model = "gbargento7f", price = 130000, category = "sedans", image = "gbargento7f.webp" },
        ["gbeon"] = { name = "Eon", brand = "Coil", model = "gbeon", price = 100000, category = "sedans", image = "gbeon.webp" },
        ["gbhades"] = { name = "Hades (2009)", brand = "Dundreary", model = "gbhades", price = 40000, category = "sedans", image = "gbhades.webp" },
        ["gbharmann"] = { name = "Harmann", brand = "Benefactor", model = "gbharmann", price = 100000, category = "sedans", image = "gbharmann.webp" },
        ["gbimpaler"] = { name = "Impaler (2009)", brand = "Declasse", model = "gbimpaler", price = 40000, category = "sedans", image = "gbimpaler.webp" },
        ["gbkomodagt"] = { name = "Komoda GT", brand = "Lampadati", model = "gbkomodagt", price = 100000, category = "sedans", image = "gbkomodagt.webp" },
        ["gbschrauber"] = { name = "Schrauber", brand = "Benefactor", model = "gbschrauber", price = 100000, category = "sedans", image = "gbschrauber.webp" },
        ["gbstanierle"] = { name = "Stanier LE", brand = "Vapid", model = "gbstanierle", price = 30000, category = "sedans", image = "gbstanierle.webp" },
        ["gbtaxiargento7f"] = { name = "Taxi Argento 7F", brand = "Obey", model = "gbtaxiargento7f", price = 100000, category = "sedans", image = "gbtaxiargento7f.webp" },
        ["gbtaxieon"] = { name = "Taxi Eon", brand = "Coil", model = "gbtaxieon", price = 70000, category = "sedans", image = "gbtaxieon.webp" },
        ["gbtaxistanierle"] = { name = "Taxi Stanier LE", brand = "Vapid", model = "gbtaxistanierle", price = 20000, category = "sedans", image = "gbtaxistanierle.webp" },
        ["interceptor"] = { name = "Interceptor", brand = "Vapid", model = "interceptor", price = 39338, category = "sedans", image = "interceptor.webp" },
        ["jd_oraclev12"] = { name = "Oracle V12", brand = "Ubermacht", model = "jd_oraclev12", price = 75192, category = "sedans", image = "jd_oraclev12.webp" },
        ["jd_oraclev12w"] = { name = "Oracle V12 Touring", brand = "Ubermacht", model = "jd_oraclev12w", price = 75192, category = "sedans", image = "jd_oraclev12w.webp" },
        ["jd_oraclexsv12"] = { name = "Oracle XS V12", brand = "Ubermacht", model = "jd_oraclexsv12", price = 75192, category = "sedans", image = "jd_oraclexsv12.webp" },
        ["jd_oraclexsv12w"] = { name = "Oracle XS V12 Touring", brand = "Ubermacht", model = "jd_oraclexsv12w", price = 75192, category = "sedans", image = "jd_oraclexsv12w.webp" },
        ["jefferson"] = { name = "Jefferson (1996)", brand = "Dundreary", model = "jefferson", price = 28897, category = "sedans", image = "jefferson.webp" },
        ["olympus"] = { name = "Olympus", brand = "Albany", model = "olympus", price = 174148, category = "sedans", image = "olympus.webp" },
        ["onx_ambassador"] = { name = "Ambassador", brand = "Cheval", model = "onx_ambassador", price = 25000, category = "sedans", image = "onx_ambassador.webp" },
        ["onx_buffaloac"] = { name = "Buffalo AC", brand = "Bravado", model = "onx_buffaloac", price = 30000, category = "sedans", image = "onx_buffaloac.webp" },
        ["onx_buffalohf"] = { name = "Buffalo HF", brand = "Bravado", model = "onx_buffalohf", price = 32000, category = "sedans", image = "onx_buffalohf.webp" },
        ["onx_buffalostx8"] = { name = "Buffalo STX8 (2010)", brand = "Bravado", model = "onx_buffalostx8", price = 38000, category = "sedans", image = "onx_buffalostx8.webp" },
        ["onx_merit1"] = { name = "Merit Classic", brand = "Declasse", model = "onx_merit1", price = 18897, category = "sedans", image = "onx_merit1.webp" },
        ["onx_merit2"] = { name = "Merit Cruiser", brand = "Declasse", model = "onx_merit2", price = 23897, category = "sedans", image = "onx_merit2.webp" },
        ["onx_merit3"] = { name = "Merit (2015)", brand = "Declasse", model = "onx_merit3", price = 28000, category = "sedans", image = "onx_merit3.webp" },
        ["onx_tavros"] = { name = "Tavros", brand = "Albany", model = "onx_tavros", price = 27000, category = "sedans", image = "onx_tavros.webp" },
        ["oraclelwb"] = { name = "Oracle LWB", brand = "Ubermacht", model = "oraclelwb", price = 74148, category = "sedans", image = "oraclelwb.webp" },
        ["oracxsle"] = { name = "Oracle XS LE", brand = "Ubermacht", model = "oracxsle", price = 94148, category = "sedans", image = "oracxsle.webp" },
        ["pmp600"] = { name = "PMP 600", brand = "Schyster", model = "pmp600", price = 69338, category = "sedans", image = "pmp600.webp" },
        ["pmp900"] = { name = "PMP 900", brand = "Schyster", model = "pmp900", price = 89338, category = "sedans", image = "pmp900.webp" },
        ["schweizer"] = { name = "Schweizer", brand = "Benefactor", model = "schweizer", price = 62476, category = "sedans", image = "schweizer.webp" },
        ["schweizer2"] = { name = "Schweizer GT", brand = "Benefactor", model = "schweizer2", price = 62476, category = "sedans", image = "schweizer2.webp" },
        ["seraph10"] = { name = "Seraph XS", brand = "Ubermacht", model = "seraph10", price = 165522, category = "sedans", image = "seraph10.webp" },
        ["taxi2"] = { name = "Merit Taxi", brand = "Declasse", model = "taxi2", price = 21835, category = "sedans", image = "taxi2.webp" },
        ["taxi3"] = { name = "Stanier Taxi", brand = "Vapid", model = "taxi3", price = 21835, category = "sedans", image = "taxi3.webp" },
        ["tfstanier"] = { name = "Stanier (2011)", brand = "Vapid", model = "tfstanier", price = 35522, category = "sedans", image = "gbstanierle.webp" },
        ["vadmiral1"] = { name = "Admiral (1989)", brand = "Benefactor", model = "vadmiral1", price = 20516, category = "sedans", image = "vadmiral1.webp" },
        ["vargento1"] = { name = "Argento", brand = "Obey", model = "vargento1", price = 280000, category = "sedans", image = "vargento1.webp" },
        ["vcognoscenti1"] = { name = "Cognoscenti I", brand = "Enus", model = "vcognoscenti1", price = 85522, category = "sedans", image = "vcognoscenti1.webp" },
        ["vincent"] = { name = "Vincent", brand = "Maibatsu", model = "vincent", price = 21835, category = "sedans", image = "vincent.webp" },
        ["vincent2"] = { name = "Vincent Sport", brand = "Maibatsu", model = "vincent2", price = 31835, category = "sedans", image = "vincent2.webp" },
        ["vors"] = { name = "Pullfrau", brand = "Benefactor", model = "vors", price = 85522, category = "sedans", image = "vors.webp" },
        ["vstdstanier1"] = { name = "STD Stanier", brand = "Vapid", model = "vstdstanier1", price = 23587, category = "sedans", image = "vstdstanier1.webp" },
        ["vstreiter1"] = { name = "Streiter", brand = "Benefactor", model = "vstreiter1", price = 71204, category = "sedans", image = "vstreiter1.webp" },
    },
    ["suvs"] = {
        ["aleutianxl"] = { name = "Aleutian XL", brand = "Vapid", model = "aleutianxl", price = 85522, category = "suvs", image = "aleutianxl.webp" },
        ["algoserrano"] = { name = "Serrano XLT", brand = "Benefactor", model = "algoserrano", price = 60000, category = "suvs" },
        ["atlas"] = { name = "Atlas", brand = "Karin", model = "atlas", price = 25000, category = "suvs", image = "atlas.webp" },
        ["ballerc"] = { name = "Baller (1976)", brand = "Gallivanter", model = "ballerc", price = 25522, category = "suvs", image = "ballerc.webp" },
        ["contender2"] = { name = "Contender", brand = "Vapid", model = "contender2", price = 185522, category = "suvs", image = "contender2.webp" },
        ["executioner"] = { name = "Executioner (2002)", brand = "Vapid", model = "executioner", price = 25522, category = "suvs", image = "executioner.webp" },
        ["fxt"] = { name = "Cavalcade FXT (2006)", brand = "Albany", model = "fxt", price = 65522, category = "suvs", image = "fxt.webp" },
        ["gbgresleystx"] = { name = "Gresley STX (2021)", brand = "Bravado", model = "gbgresleystx", price = 80000, category = "suvs", image = "gbgresleystx.webp" },
        ["gbstarlight"] = { name = "Starlight", brand = "Vulcar", model = "gbstarlight", price = 100000, category = "suvs", image = "gbstarlight.webp" },
        ["gbtaxistarlight"] = { name = "Taxi Starlight", brand = "Vulcar", model = "gbtaxistarlight", price = 80000, category = "suvs", image = "gbtaxistarlight.webp" },
        ["granger3"] = { name = "Granger (1998)", brand = "Declasse", model = "granger3", price = 25522, category = "suvs", image = "granger3.webp" },
        ["gresleyh"] = { name = "Gresley Hellhound", brand = "Bravado", model = "gresleyh", price = 55522, category = "suvs", image = "gresleyh.webp" },
        ["gstgrs1"] = { name = "Gresley (2018)", brand = "Bravado", model = "gstgrs1", price = 85522, category = "suvs", image = "gstgrs1.webp" },
        ["gstgrs1b"] = { name = "Gresley Custom (2018)", brand = "Bravado", model = "gstgrs1b", price = 185522, category = "suvs", image = "gstgrs1b.webp" },
        ["gstvle1"] = { name = "Vivanite Custom", brand = "Karin", model = "gstvle1", price = 1805000, category = "suvs", image = "gstvle1.webp" },
        ["hellion2"] = { name = "Hellion II", brand = "Annis", model = "hellion2", price = 25522, category = "suvs", image = "hellion2.webp" },
        ["huntley2"] = { name = "Huntley Sport", brand = "Vapid", model = "huntley2", price = 35522, category = "suvs", image = "huntley2.webp" },
        ["nriata2"] = { name = "Riata (2024)", brand = "Vapid", model = "nriata2", price = 55522, category = "suvs", image = "nriata2.webp" },
        ["nscout"] = { name = "Scout (2020)", brand = "Vapid", model = "nscout", price = 45522, category = "suvs", image = "nscout.webp" },
        ["onx_doradost"] = { name = "Dorado AC", brand = "Bravado", model = "onx_doradost", price = 48000, category = "suvs", image = "onx_doradost.webp" },
        ["onx_granger"] = { name = "Granger Classic", brand = "Declasse", model = "onx_granger", price = 45000, category = "suvs", image = "onx_granger.webp" },
        ["onx_scout25"] = { name = "Scout (2025)", brand = "Vapid", model = "onx_scout25", price = 43000, category = "suvs", image = "onx_scout25.webp" },
        ["onx_scoutc"] = { name = "Scout (1993)", brand = "Vapid", model = "onx_scoutc", price = 25522, category = "suvs", image = "onx_scoutc.webp" },
        ["rablaiv"] = { name = "Rabla IV", brand = "Ubermacht", model = "rablaiv", price = 25522, category = "suvs", image = "reblaiv.webp" },
        ["riata3"] = { name = "Riata (1985)", brand = "Vapid", model = "riata3", price = 15522, category = "suvs", image = "riata3.webp" },
        ["riata4"] = { name = "Riata (1996)", brand = "Vapid", model = "riata4", price = 19522, category = "suvs", image = "riata4.webp" },
        ["scout"] = { name = "Scout (2013)", brand = "Vapid", model = "scout", price = 25522, category = "suvs", image = "scout.webp" },
        ["scoutc"] = { name = "Scout (1991)", brand = "Vapid", model = "scoutc", price = 22522, category = "suvs", image = "scoutc.webp" },
        ["tfalamo"] = { name = "Alamo 2700LX (2024)", brand = "Declasse", model = "tfalamo", price = 55522, category = "suvs", image = "tfalamo.webp" },
        ["tfgranger"] = { name = "Granger 3700LX (2024)", brand = "Declasse", model = "tfgranger", price = 65522, category = "suvs", image = "tfgranger.webp" },
        ["tfregent"] = { name = "Regent (2024)", brand = "Brute", model = "tfregent", price = 75522, category = "suvs", image = "tfregent.webp" },
        ["tfregentxl"] = { name = "Regent XL (2024)", brand = "Brute", model = "tfregentxl", price = 65522, category = "suvs", image = "tfregentxl.webp" },
        ["valamo1"] = { name = "Alamo (2003)", brand = "Declasse", model = "valamo1", price = 29522, category = "suvs", image = "valamo1.webp" },
        ["valamo2"] = { name = "Alamo (2009)", brand = "Declasse", model = "valamo2", price = 45522, category = "suvs", image = "valamo2.webp" },
        ["valamo3"] = { name = "Alamo (1994)", brand = "Declasse", model = "valamo3", price = 25522, category = "suvs", image = "valamo3.webp" },
    },
    ["muscle"] = {
        ["admiral3"] = { name = "Admiral (1985)", brand = "Dundreary", model = "admiral3", price = 20516, category = "muscle", image = "admiral3.webp" },
        ["ametista"] = { name = "Ametista Wagon (1979)", brand = "Declasse", model = "ametista", price = 27450, category = "muscle", image = "ametista.webp" },
        ["buffalo4h"] = { name = "Buffalo Hellfire", brand = "Bravado", model = "buffalo4h", price = 80516, category = "muscle", image = "buffalo4h.webp" },
        ["domgtcoupe"] = { name = "Dominator GT Coupe (2022)", brand = "Vapid", model = "domgtcoupe", price = 62702, category = "muscle", image = "domgtcoupe.webp" },
        ["gauntletc"] = { name = "Gauntlet Classic Custom (1968)", brand = "Bravado", model = "gauntletc", price = 61665, category = "muscle", image = "gauntletc.webp" },
        ["gauntlets"] = { name = "Gauntlet S (2023)", brand = "Bravado", model = "gauntlets", price = 81665, category = "muscle", image = "gauntlets.webp" },
        ["gauntletstx"] = { name = "Gauntlet STX", brand = "Bravado", model = "gauntletstx", price = 68237, category = "muscle", image = "gauntletstx.webp" },
        ["gbdominatorgsx"] = { name = "Dominator GSX", brand = "Vapid", model = "gbdominatorgsx", price = 70000, category = "muscle", image = "gbdominatorgsx.webp" },
        ["gbtahomagt"] = { name = "Tahoma GT", brand = "Declasse", model = "gbtahomagt", price = 100000, category = "muscle", image = "gbtahomagt.webp" },
        ["gstbufst1"] = { name = "Buffalo ST (2015)", brand = "Bravado", model = "gstbufst1", price = 50516, category = "muscle", image = "gstbufst1.webp" },
        ["gwoods"] = { name = "Greenwood", brand = "Schyster", model = "gwoods", price = 18897, category = "muscle", image = "gwoods.webp" },
        ["idaho"] = { name = "Idaho (1977)", brand = "Willard", model = "idaho", price = 18897, category = "muscle", image = "idaho.webp" },
        ["librac"] = { name = "Libra LC", brand = "Bravado", model = "librac", price = 69338, category = "muscle", image = "librac.webp" },
        ["libracc"] = { name = "Libra LXC", brand = "Bravado", model = "libracc", price = 69338, category = "muscle", image = "libracc.webp" },
        ["libracust"] = { name = "Libra Custom", brand = "Bravado", model = "libracust", price = 89338, category = "muscle", image = "libracust.webp" },
        ["libras"] = { name = "Libra LS", brand = "Bravado", model = "libras", price = 69338, category = "muscle", image = "libras.webp" },
        ["libraw"] = { name = "Libra LW", brand = "Bravado", model = "libraw", price = 69338, category = "muscle", image = "libraw.webp" },
        ["libraw2"] = { name = "Libra LXW", brand = "Bravado", model = "libraw2", price = 69338, category = "muscle", image = "libraw2.webp" },
        ["onx_domgtcoupe"] = { name = "Dominator GT (2024)", brand = "Vapid", model = "onx_domgtcoupe", price = 62702, category = "muscle", image = "onx_domgtcoupe.webp" },
        ["onx_tulip2c"] = { name = "Tulip Custom", brand = "Declasse", model = "onx_tulip2c", price = 42000, category = "muscle", image = "onx_tulip2c.webp" },
        ["paradox"] = { name = "Paradox (1969)", brand = "Willard", model = "paradox", price = 24148, category = "muscle", image = "paradox.webp" },
        ["paradox2"] = { name = "Paradox Custom (1969)", brand = "Willard", model = "paradox2", price = 32148, category = "muscle", image = "paradox2.webp" },
        ["phoenix2"] = { name = "Phoenix 455 RS (1977)", brand = "Imponte", model = "phoenix2", price = 250000, category = "muscle" },
        ["picadorexr"] = { name = "Picador EXR", brand = "Cheval", model = "picadorexr", price = 47839, category = "muscle", image = "picadorexr.webp" },
        ["sabre"] = { name = "Sabre 550 SS (1985)", brand = "Declasse", model = "sabre", price = 47450, category = "muscle", image = "sabre.webp" },
        ["sabre2"] = { name = "Sabre Beater (1985)", brand = "Declasse", model = "sabre2", price = 27450, category = "muscle", image = "sabre2.webp" },
        ["tulip3"] = { name = "Tulip SS (1968)", brand = "Declasse", model = "tulip3", price = 64746, category = "muscle", image = "tulip3.webp" },
        ["turmalina"] = { name = "Turmalina Coupe (1979)", brand = "Declasse", model = "turmalina", price = 27450, category = "muscle", image = "turmalina.webp" },
        ["turmalina2"] = { name = "Turmalina (1979)", brand = "Declasse", model = "turmalina2", price = 27450, category = "muscle", image = "turmalina2.webp" },
        ["vigeronew"] = { name = "Vigero ZL-1 (2020)", brand = "Declasse", model = "vigeronew", price = 100000, category = "muscle", image = "vigeronew.webp" },
        ["vpicador1"] = { name = "Picador II", brand = "Cheval", model = "vpicador1", price = 67839, category = "muscle", image = "vpicador1.webp" },
        ["vulture"] = { name = "Vulture (1969)", brand = "Bravado", model = "vulture", price = 50516, category = "muscle", image = "vulture.webp" },
    },
    ["sports"] = {
        ["cometold"] = { name = "Comet S2 Classic", brand = "Pfister", model = "cometold", price = 183378, category = "sports", image = "cometold.webp" },
        ["contenderc"] = { name = "Contender Custom", brand = "Vapid", model = "contenderc", price = 98578, category = "sports", image = "contenderc.webp" },
        ["elegyheritage"] = { name = "Elegy RH5 Heritage", brand = "Annis", model = "elegyheritage", price = 78735, category = "sports", image = "elegyheritage.webp" },
        ["elegyrace"] = { name = "Elegy RH5-R", brand = "Annis", model = "elegyrace", price = 78735, category = "sports", image = "elegyrace.webp" },
        ["elegyrh7"] = { name = "Elegy RH7", brand = "Annis", model = "elegyrh7", price = 80339, category = "sports", image = "elegyrh7.webp" },
        ["elegyrh72"] = { name = "Elegy RH7 RHD", brand = "Annis", model = "elegyrh72", price = 80339, category = "sports", image = "elegyrh72.webp" },
        ["es550"] = { name = "ES-550", brand = "Annis", model = "es550", price = 80250, category = "sports", image = "es550.webp" },
        ["gbmogulrs"] = { name = "Mogul RS", brand = "Karin", model = "gbmogulrs", price = 60000, category = "sports", image = "gbmogulrs.webp" },
        ["gbraidillon"] = { name = "Raidillon", brand = "Toundra", model = "gbraidillon", price = 100000, category = "sports", image = "gbraidillon.webp" },
        ["gbschlagenr"] = { name = "Schlagen R", brand = "Benefactor", model = "gbschlagenr", price = 100000, category = "sports", image = "gbschlagenr.webp" },
        ["gbschlagensp"] = { name = "Schlagen SP", brand = "Benefactor", model = "gbschlagensp", price = 100000, category = "sports", image = "gbschlagensp.webp" },
        ["gbschwartzers"] = { name = "Schwartzer S", brand = "Benefactor", model = "gbschwartzers", price = 100000, category = "sports", image = "gbschwartzers.webp" },
        ["gbsultanrsx"] = { name = "Sultan RSx", brand = "Karin", model = "gbsultanrsx", price = 62000, category = "sports", image = "gbsultanrsx.webp" },
        ["gstsulbe1"] = { name = "Sultan BE", brand = "Karin", model = "gstsulbe1", price = 54392, category = "sports", image = "gstsulbe1.webp" },
        ["gstter2"] = { name = "Terenowa STR", brand = "Karin", model = "gstter2", price = 77445, category = "sports", image = "gstter2.webp" },
        ["nwjester"] = { name = "Jester S (1993)", brand = "Dinka", model = "nwjester", price = 76685, category = "sports", image = "nwjester.webp" },
        ["nwkuruma"] = { name = "Kuruma Widebody", brand = "Karin", model = "nwkuruma", price = 135522, category = "sports", image = "nwkuruma.webp" },
        ["raidenz"] = { name = "Raiden Z", brand = "Coil", model = "raidenz", price = 124370, category = "sports", image = "raidenz.webp" },
        ["recursion"] = { name = "Recursion", brand = "Bravado", model = "recursion", price = 24370, category = "sports", image = "recursion.webp" },
        ["remustwo"] = { name = "Remus II", brand = "Annis", model = "remustwo", price = 1370000, category = "sports", image = "remustwo.webp" },
        ["remusvert"] = { name = "Remus Convertible", brand = "Annis", model = "remusvert", price = 1370000, category = "sports", image = "remusvert.webp" },
        ["stardust"] = { name = "Stardust", brand = "Pfister", model = "stardust", price = 80250, category = "sports", image = "stardust.webp" },
        ["sunrise1"] = { name = "Sunrise", brand = "Maibatsu", model = "sunrise1", price = 43972, category = "sports", image = "sunrise1.webp" },
        ["supergt"] = { name = "Super GT", brand = "Dewbauchee", model = "supergt", price = 80250, category = "sports", image = "supergt.webp" },
        ["vesper"] = { name = "Vesper", brand = "Dewbauchee", model = "vesper", price = 83972, category = "sports", image = "vesper.webp" },
        ["vs2301"] = { name = "S-230", brand = "Annis", model = "vs2301", price = 80250, category = "sports" },
        ["vzr1501"] = { name = "ZR-150", brand = "Annis", model = "vzr1501", price = 80250, category = "sports" },
        ["vzr3501"] = { name = "ZR-350", brand = "Annis", model = "vzr3501", price = 80250, category = "sports" },
        ["vzr3801"] = { name = "ZR-380", brand = "Annis", model = "vzr3801", price = 80250, category = "sports" },
        ["zr250"] = { name = "ZR-250 Savestra", brand = "Annis", model = "zr250", price = 80250, category = "sports" },
    },
    ["sportsclassic"] = {
        ["cheetahfel"] = { name = "Cheetah Feloci", brand = "Grotti", model = "cheetahfel", price = 282927, category = "sportsclassic", image = "cheetahfel.webp" },
        ["deluxowb2"] = { name = "Deluxo Widebody", brand = "Imponte", model = "deluxowb2", price = 4721500, category = "sportsclassic", image = "deluxowb2.webp" },
        ["gbsidewinder"] = { name = "Sidewinder", brand = "Maxwell", model = "gbsidewinder", price = 100000, category = "sportsclassic", image = "gbsidewinder.webp" },
        ["strage"] = { name = "Strage", brand = "Dewbauchee", model = "strage", price = 45522, category = "sportsclassic", image = "strage.webp" },
        ["velena1"] = { name = "Elena", brand = "Ocelot", model = "velena1", price = 71685, category = "sportsclassic", image = "velena1.webp" },
    },
    ["super"] = {
        ["cycloneex0"] = { name = "Cyclone EX-0", brand = "Coil", model = "cycloneex0", price = 268875, category = "super", image = "cycloneex0.webp" },
        ["gb811s2"] = { name = "811 S2", brand = "Pfister", model = "gb811s2", price = 100000, category = "super", image = "gb811s2.webp" },
        ["gbbanshees"] = { name = "Banshee S", brand = "Bravado", model = "gbbanshees", price = 100000, category = "super", image = "gbbanshees.webp" },
        ["gbcometcl"] = { name = "Comet Classic", brand = "Pfister", model = "gbcometcl", price = 100000, category = "super", image = "gbcometcl.webp" },
        ["gbcomets1t"] = { name = "Comet S1T", brand = "Pfister", model = "gbcomets1t", price = 100000, category = "super", image = "gbcomets1t.webp" },
        ["gbcomets2r"] = { name = "Comet S2R", brand = "Pfister", model = "gbcomets2r", price = 100000, category = "super", image = "gbcomets2r.webp" },
        ["gbcomets2rc"] = { name = "Comet S2R Cabrio", brand = "Pfister", model = "gbcomets2rc", price = 100000, category = "super", image = "gbcomets2rc.webp" },
        ["gbemerussb1"] = { name = "Emerus SB1", brand = "Unknown brand", model = "gbemerussb1", price = 100000, category = "super", image = "gbemerussb1.webp" },
        ["gbmilano"] = { name = "Milano", brand = "Grotti", model = "gbmilano", price = 100000, category = "super", image = "gbmilano.webp" },
        ["gbneonct"] = { name = "Neon CT", brand = "Coil", model = "gbneonct", price = 100000, category = "super", image = "gbneonct.webp" },
        ["gbnexusrr"] = { name = "Nexus RR", brand = "Dinka", model = "gbnexusrr", price = 100000, category = "super", image = "gbnexusrr.webp" },
        ["gbprospero"] = { name = "Prospero", brand = "Pegassi", model = "gbprospero", price = 100000, category = "super", image = "gbprospero.webp" },
        ["gbronin"] = { name = "Ronin", brand = "Emperor", model = "gbronin", price = 100000, category = "super", image = "gbronin.webp" },
        ["gbsolace"] = { name = "Solace", brand = "Dewbauchee", model = "gbsolace", price = 100000, category = "super", image = "gbsolace.webp" },
        ["gbsolacev"] = { name = "Solace V", brand = "Dewbauchee", model = "gbsolacev", price = 100000, category = "super", image = "gbsolacev.webp" },
        ["gbtenfr"] = { name = "10F R", brand = "Obey", model = "gbtenfr", price = 100000, category = "super", image = "gbtenfr.webp" },
        ["gbtr3s"] = { name = "TR3 S", brand = "Progen", model = "gbtr3s", price = 100000, category = "super", image = "gbtr3s.webp" },
        ["gbturismogt"] = { name = "Turismo GT", brand = "Grotti", model = "gbturismogt", price = 100000, category = "super", image = "gbturismogt.webp" },
        ["gbturismogts"] = { name = "Turismo GTS", brand = "Grotti", model = "gbturismogts", price = 100000, category = "super", image = "gbturismogts.webp" },
        ["onx_coquetted9"] = { name = "Coquette D9", brand = "Invetero", model = "onx_coquetted9", price = 140000, category = "super", image = "onx_coquetted9.webp" },
        ["sc_infernusx"] = { name = "Infernus SX (2002)", brand = "Pegassi", model = "sc_infernusx", price = 281077, category = "super", image = "sc_infernusx.webp" },
        ["tempestaes"] = { name = "Tempesta EVO Stradale", brand = "Pegassi", model = "tempestaes", price = 1329000, category = "super" },
        ["vcheetah1"] = { name = "Cheetah R", brand = "Grotti", model = "vcheetah1", price = 280000, category = "super", image = "vcheetah1.webp" },
        ["vspritzer1"] = { name = "Spritzer STR", brand = "Benefactor", model = "vspritzer1", price = 78839, category = "super", image = "vspritzer1.webp" },
    },
    ["motorcycles"] = {
        ["bati901"] = { name = "Bati 901", brand = "Pegassi", model = "bati901", price = 25838, category = "motorcycles", image = "bati901.webp" },
        ["batic"] = { name = "Bati 801C", brand = "Pegassi", model = "batic", price = 25838, category = "motorcycles", image = "batic.webp" },
        ["chunkster"] = { name = "Chunkster", brand = "Western", model = "chunkster", price = 23182, category = "motorcycles", image = "chunkster.webp" },
        ["onx_kandra"] = { name = "Kandra", brand = "Karin", model = "onx_kandra", price = 22000, category = "motorcycles", image = "onx_kandra.webp" },
        ["speedstercr"] = { name = "Speedster Custom", brand = "Western", model = "speedstercr", price = 23182, category = "motorcycles", image = "speedstercr.webp" },
        ["zombiev8"] = { name = "Zombie V8", brand = "Western", model = "zombiev8", price = 23182, category = "motorcycles", image = "zombiev8.webp" },
    },
    ["off-road"] = {
        ["bjxlr"] = { name = "BeeJay XL-R", brand = "Karin", model = "bjxlr", price = 85522, category = "off-road", image = "bjxlr.webp" },
        ["blazer6"] = { name = "Blazer RECON", brand = "Nagasaki", model = "blazer6", price = 55600, category = "off-road", image = "blazer6.webp" },
        ["burritopw"] = { name = "Burrito PowerWheel", brand = "Unknown brand", model = "burritopw", price = 19338, category = "off-road", image = "burritopw.webp" },
        ["dubstab"] = { name = "Dubsta B-Wagon", brand = "Benefactor", model = "dubstab", price = 82617, category = "off-road", image = "dubstab.webp" },
        ["duness"] = { name = "Dune Kart", brand = "BF", model = "duness", price = 25000, category = "off-road", image = "duness.webp" },
        ["executioner2"] = { name = "Executioner (1985)", brand = "Vapid", model = "executioner2", price = 65522, category = "off-road", image = "executioner2.webp" },
        ["executioner3"] = { name = "Executioner (1997)", brand = "Vapid", model = "executioner3", price = 65522, category = "off-road", image = "executioner3.webp" },
        ["h4rxgranut"] = { name = "Granger Utility", brand = "Declasse", model = "h4rxgranut", price = 85522, category = "off-road", image = "h4rxgranut.webp" },
        ["mesaxl"] = { name = "Mesa Gator", brand = "Canis", model = "mesaxl", price = 85522, category = "off-road", image = "mesaxl.webp" },
        ["nriata"] = { name = "Riata Offroad (2024)", brand = "Vapid", model = "nriata", price = 85522, category = "off-road", image = "nriata.webp" },
        ["onx_guardian"] = { name = "Guardian", brand = "Vapid", model = "onx_guardian", price = 70000, category = "off-road", image = "onx_guardian.webp" },
        ["onx_guardian2"] = { name = "Guardian 2", brand = "Vapid", model = "onx_guardian2", price = 70000, category = "off-road", image = "onx_guardian2.webp" },
        ["onx_guardian3"] = { name = "Guardian 3", brand = "Vapid", model = "onx_guardian3", price = 70000, category = "off-road", image = "onx_guardian3.webp" },
        ["onx_guardian4"] = { name = "Guardian 4", brand = "Vapid", model = "onx_guardian4", price = 70000, category = "off-road", image = "onx_guardian4.webp" },
        ["onx_invictus"] = { name = "Invictus", brand = "Canis", model = "onx_invictus", price = 42000, category = "off-road", image = "onx_invictus.webp" },
        ["onx_invictus2"] = { name = "Invictus Mk2", brand = "Canis", model = "onx_invictus2", price = 46000, category = "off-road", image = "onx_invictus2.webp" },
        ["onx_terminus2"] = { name = "Terminus", brand = "Vapid", model = "onx_terminus2", price = 60000, category = "off-road", image = "onx_terminus2.webp" },
        ["onx_verus"] = { name = "Verus", brand = "Dinka", model = "onx_verus", price = 70000, category = "off-road", image = "onx_verus.webp" },
        ["patriot3a"] = { name = "Patriot M1", brand = "Mammoth", model = "patriot3a", price = 1710000, category = "off-road", image = "patriot3a.webp" },
        ["patriots"] = { name = "Patriot Sport", brand = "Mammoth", model = "patriots", price = 85522, category = "off-road", image = "patriots.webp" },
        ["patriots2"] = { name = "Patriot Sport MilSpec", brand = "Mammoth", model = "patriots2", price = 85522, category = "off-road", image = "patriots2.webp" },
        ["peacemaker"] = { name = "Peacemaker Estate", brand = "Gallivanter", model = "peacemaker", price = 65522, category = "off-road", image = "peacemaker2.webp" },
        ["peacemaker2"] = { name = "Peacemaker Pickup", brand = "Gallivanter", model = "peacemaker2", price = 85522, category = "off-road", image = "peacemaker2.webp" },
        ["peacemaker3"] = { name = "Peacemaker", brand = "Gallivanter", model = "peacemaker3", price = 85522, category = "off-road", image = "peacemaker2.webp" },
        ["peacemaker4"] = { name = "Peacemaker Outlander Pickup", brand = "Gallivanter", model = "peacemaker4", price = 65522, category = "off-road", image = "peacemaker2.webp" },
        ["peacemaker5"] = { name = "Peacemaker Outlander 6x6", brand = "Gallivanter", model = "peacemaker5", price = 65522, category = "off-road", image = "peacemaker2.webp" },
        ["peacemaker6"] = { name = "Peacemaker Safari", brand = "Gallivanter", model = "peacemaker6", price = 65522, category = "off-road", image = "peacemaker2.webp" },
        ["raider"] = { name = "Raider", brand = "Karin", model = "raider", price = 65522, category = "off-road", image = "raider.webp" },
        ["rancher"] = { name = "Rancher I", brand = "Declasse", model = "rancher", price = 65522, category = "off-road", image = "rancher.webp" },
        ["vcoyote1"] = { name = "Coyote", brand = "Vapid", model = "vcoyote1", price = 280000, category = "off-road", image = "vcoyote1.webp" },
        ["vcoyote2"] = { name = "Coyote II", brand = "Vapid", model = "vcoyote2", price = 280000, category = "off-road", image = "vcoyote2.webp" },
        ["vdubsta1"] = { name = "Dubsta Offroad", brand = "Benefactor", model = "vdubsta1", price = 62617, category = "off-road", image = "vdubsta1.webp" },
    },
    ["trucks"] = {
        ["caracara6x6"] = { name = "Caracara 6x6", brand = "Vapid", model = "caracara6x6", price = 63685, category = "trucks", image = "caracara6x6.webp" },
        ["caracaran"] = { name = "Caracara (2020)", brand = "Vapid", model = "caracaran", price = 65522, category = "trucks", image = "caracaran.webp" },
        ["dloader5"] = { name = "Duneloader Crew", brand = "Bravado", model = "dloader5", price = 31896, category = "trucks", image = "dloader5.webp" },
        ["e109"] = { name = "Contender Sport", brand = "Vapid", model = "e109", price = 85522, category = "trucks", image = "contender2.webp" },
        ["everonb"] = { name = "Everon", brand = "Karin", model = "everonb", price = 65522, category = "trucks", image = "everonb.webp" },
        ["gbbisonhf"] = { name = "Bison Hellfire (2024)", brand = "Bravado", model = "gbbisonhf", price = 100000, category = "trucks", image = "gbbisonhf.webp" },
        ["gbbisonstx"] = { name = "Bison STX (2023)", brand = "Bravado", model = "gbbisonstx", price = 100000, category = "trucks", image = "gbbisonstx.webp" },
        ["gblod4"] = { name = "LOD4", brand = "Coil", model = "gblod4", price = 100000, category = "trucks", image = "gblod4.webp" },
        ["gbmojave"] = { name = "Mojave", brand = "Karin", model = "gbmojave", price = 100000, category = "trucks", image = "gbmojave.webp" },
        ["hellenstorm"] = { name = "Sandstorm Hellenbach", brand = "Vapid", model = "hellenstorm", price = 85522, category = "trucks", image = "hellenstorm.webp" },
        ["indiana"] = { name = "Indiana", brand = "Declasse", model = "indiana", price = 85522, category = "trucks", image = "indiana.webp" },
        ["indiana2"] = { name = "Indiana Lifted", brand = "Declasse", model = "indiana2", price = 85522, category = "trucks", image = "indiana2.webp" },
        ["indianaxl"] = { name = "Indiana XL", brand = "Declasse", model = "indianaxl", price = 85522, category = "trucks", image = "indianaxl.webp" },
        ["indianaxl2"] = { name = "Indiana XL Lifted", brand = "Declasse", model = "indianaxl2", price = 95522, category = "trucks", image = "indianaxl2.webp" },
        ["l35l"] = { name = "Walton L35 Longbed", brand = "Declasse", model = "l35l", price = 64429, category = "trucks", image = "l35l.webp" },
        ["l35r"] = { name = "Walton L35 Rancher", brand = "Declasse", model = "l35r", price = 64429, category = "trucks", image = "l35r.webp" },
        ["l35s"] = { name = "Walton L35 Shortbed I", brand = "Declasse", model = "l35s", price = 64429, category = "trucks", image = "l35s.webp" },
        ["nsandstorm"] = { name = "Sandstorm Crew", brand = "Vapid", model = "nsandstorm", price = 85522, category = "trucks", image = "nsandstorm.webp" },
        ["nsandstorm2"] = { name = "Sandstorm Crew Dually", brand = "Vapid", model = "nsandstorm2", price = 85522, category = "trucks", image = "nsandstorm2.webp" },
        ["nsandstorm3"] = { name = "Sandstorm Reg Cab", brand = "Vapid", model = "nsandstorm3", price = 85522, category = "trucks", image = "nsandstorm3.webp" },
        ["onx_sandking"] = { name = "Sandking D155", brand = "Vapid", model = "onx_sandking", price = 40000, category = "trucks", image = "onx_sandking.webp" },
        ["onx_sandking2"] = { name = "Sandking D155 SWB", brand = "Vapid", model = "onx_sandking2", price = 40000, category = "trucks", image = "onx_sandking2.webp" },
        ["onx_sandking3"] = { name = "Sandking D155 XL", brand = "Vapid", model = "onx_sandking3", price = 40000, category = "trucks", image = "onx_sandking3.webp" },
        ["onx_sandking4"] = { name = "Sandking D155 Compensator", brand = "Vapid", model = "onx_sandking4", price = 45000, category = "trucks", image = "onx_sandking4.webp" },
        ["onx_sandking5"] = { name = "Sandking D155 SWB Compensator", brand = "Vapid", model = "onx_sandking5", price = 45000, category = "trucks", image = "onx_sandking5.webp" },
        ["onx_sandking6"] = { name = "Sandking D155 XL Compensator", brand = "Vapid", model = "onx_sandking6", price = 45000, category = "trucks", image = "onx_sandking6.webp" },
        ["onx_sandstorm"] = { name = "Sandstorm", brand = "Canis", model = "onx_sandstorm", price = 38000, category = "trucks", image = "onx_sandstorm.webp" },
        ["onx_sandstorm2"] = { name = "Sandstorm Mk2", brand = "Canis", model = "onx_sandstorm2", price = 41000, category = "trucks", image = "onx_sandstorm2.webp" },
        ["onx_sandstormh"] = { name = "Sandstorm Hellenbach", brand = "Canis", model = "onx_sandstormh", price = 47000, category = "trucks", image = "onx_sandstormh.webp" },
        ["onx_sandstormxl"] = { name = "Sandstorm XL", brand = "Canis", model = "onx_sandstormxl", price = 50000, category = "trucks", image = "onx_sandstormxl.webp" },
        ["onx_tfbison"] = { name = "Bison 35XD (2019-2024)", brand = "Bravado", model = "onx_tfbison", price = 100000, category = "trucks", image = "onx_tfbison.webp" },
        ["onx_tfbison2"] = { name = "Bison 25XD SWB (2019-2024)", brand = "Bravado", model = "onx_tfbison2", price = 100000, category = "trucks", image = "onx_tfbison2.webp" },
        ["onx_tfbison3"] = { name = "Bison 45XD XL Dually (2019-2024)", brand = "Bravado", model = "onx_tfbison3", price = 100000, category = "trucks", image = "onx_tfbison3.webp" },
        ["onx_tfbison4"] = { name = "Bison 35XD Sasquatch (2019-2024)", brand = "Bravado", model = "onx_tfbison4", price = 100000, category = "trucks", image = "onx_tfbison4.webp" },
        ["sadler4"] = { name = "Sadler ShortBed (1985)", brand = "Vapid", model = "sadler4", price = 62297, category = "trucks", image = "sadler4.webp" },
        ["sadler5"] = { name = "Sadler LongBed (1985)", brand = "Vapid", model = "sadler5", price = 62297, category = "trucks", image = "sadler5.webp" },
        ["sadler9"] = { name = "Sadler CrewCab (1985)", brand = "Vapid", model = "sadler9", price = 62297, category = "trucks", image = "sadler9.webp" },
        ["sandking3"] = { name = "Sandking 4500", brand = "Vapid", model = "sandking3", price = 45522, category = "trucks", image = "sandking3.webp" },
        ["sandkingd"] = { name = "Sandking Dually Custom", brand = "Vapid", model = "sandkingd", price = 85522, category = "trucks", image = "sandkingd.webp" },
        ["tgrcara"] = { name = "Caracara Sport (2015)", brand = "Vapid", model = "tgrcara", price = 63685, category = "trucks", image = "tgrcara.webp" },
        ["vdloader1"] = { name = "Mastadon", brand = "Bravado", model = "vdloader1", price = 31896, category = "trucks", image = "vdloader1.webp" },
        ["vsadler1"] = { name = "Sadler CrewCab Dually", brand = "Vapid", model = "vsadler1", price = 62297, category = "trucks", image = "vsadler1.webp" },
        ["vsandking1"] = { name = "Sandking CrewCab LWB", brand = "Vapid", model = "vsandking1", price = 38000, category = "trucks", image = "vsandking1.webp" },
        ["vsandking2"] = { name = "Sandking ExCab LWB", brand = "Vapid", model = "vsandking2", price = 45000, category = "trucks", image = "vsandking2.webp" },
        ["vyosemite1"] = { name = "Yosemite (1976)", brand = "Declasse", model = "vyosemite1", price = 16896, category = "trucks", image = "vyosemite1.webp" },
        ["vyosemite2"] = { name = "Yosemite CrewCab (2005)", brand = "Declasse", model = "vyosemite2", price = 46896, category = "trucks", image = "vyosemite2.webp" },
        ["vyosemite3"] = { name = "Yosemite SB (1986)", brand = "Declasse", model = "vyosemite3", price = 26896, category = "trucks", image = "vyosemite3.webp" },
        ["vyosemite4"] = { name = "Yosemite Rancher (1986)", brand = "Declasse", model = "vyosemite4", price = 21896, category = "trucks", image = "vyosemite4.webp" },
        ["vyosemite5"] = { name = "Yosemite CrewCab (1986)", brand = "Declasse", model = "vyosemite5", price = 19896, category = "trucks", image = "vyosemite5.webp" },
        ["vyosemitexl1"] = { name = "Yosemite Rancher XL (1986)", brand = "Declasse", model = "vyosemitexl1", price = 26896, category = "trucks", image = "vyosemitexl1.webp" },
        ["vyosemitexl2"] = { name = "Yosemite Dually (1986)", brand = "Declasse", model = "vyosemitexl2", price = 26896, category = "trucks", image = "vyosemitexl2.webp" },
        ["yosemite3step"] = { name = "Yosemite Stepside (1975)", brand = "Declasse", model = "yosemite3step", price = 100000, category = "trucks", image = "yosemite3step.webp" },
        ["yosemite5"] = { name = "Yosemite Crew Cab", brand = "Brute", model = "yosemite5", price = 89338, category = "trucks", image = "yosemite5.webp" },
    },
    ["vans"] = {
        ["gbesperta"] = { name = "Esperta", brand = "Bravado", model = "gbesperta", price = 65522, category = "vans", image = "gbesperta.webp" },
        ["imperial"] = { name = "Imperial Utility", brand = "Benefactor", model = "imperial", price = 40522, category = "vans", image = "imperial.webp" },
        ["imperialev"] = { name = "Imperial EV", brand = "Benefactor", model = "imperialev", price = 65522, category = "vans", image = "imperialev.webp" },
        ["imperialpas"] = { name = "Imperial", brand = "Benefactor", model = "imperialpas", price = 55522, category = "vans", image = "imperialpas.webp" },
        ["jogger"] = { name = "Jogger", brand = "Benefactor", model = "jogger", price = 65522, category = "vans", image = "jogger.webp" },
        ["joggerpas"] = { name = "Jogger Passenger", brand = "Benefactor", model = "joggerpas", price = 65522, category = "vans", image = "joggerpas.webp" },
        ["navarra"] = { name = "Pony Navarra", brand = "Brute", model = "navarra", price = 75522, category = "vans", image = "navarra.webp" },
        ["nspeedo"] = { name = "Speedo Express", brand = "Vapid", model = "nspeedo", price = 15000, category = "vans", image = "nspeedo.webp" },
        ["runner"] = { name = "Runner", brand = "Benefactor", model = "runner", price = 65522, category = "vans", image = "runner.webp" },
        ["vbison1"] = { name = "Bison", brand = "Bravado", model = "vbison1", price = 25000, category = "vans", image = "vbison1.webp" },
        ["vbison2"] = { name = "Bison LT", brand = "Bravado", model = "vbison2", price = 30000, category = "vans", image = "vbison2.webp" },
        ["vpony1"] = { name = "Pony Retro", brand = "Brute", model = "vpony1", price = 11195, category = "vans", image = "vpony1.webp" },
        ["vpony2"] = { name = "Pony Retro", brand = "Brute", model = "vpony2", price = 11195, category = "vans", image = "vpony2.webp" },
        ["vrumpo1"] = { name = "Rumpo Retro", brand = "Bravado", model = "vrumpo1", price = 23310, category = "vans", image = "vrumpo1.webp" },
    },
    ["luxury"] = {
        ["ccadeesv"] = { name = "Cavalcade ESV (2022)", brand = "Albany", model = "ccadeesv", price = 85522, category = "luxury", image = "ccadeesv.webp" },
        ["ccadefxt"] = { name = "Cavalcade FXT (2022)", brand = "Albany", model = "ccadefxt", price = 75522, category = "luxury", image = "ccadefxt.webp" },
        ["dubsta22"] = { name = "Dubsta (2022)", brand = "Benefactor", model = "dubsta22", price = 164556, category = "luxury", image = "dubsta22.webp" },
        ["expression"] = { name = "Expression", brand = "Albany", model = "expression", price = 196110, category = "luxury", image = "expression.webp" },
        ["ncavalcade"] = { name = "Cavalcade (2024)", brand = "Albany", model = "ncavalcade", price = 75522, category = "luxury", image = "ncavalcade.webp" },
        ["superd2"] = { name = "Super Diamond Conv. (2003)", brand = "Enus", model = "superd2", price = 250000, category = "luxury" },
        ["superd3"] = { name = "Super Diamond S (2018)", brand = "Enus", model = "superd3", price = 250000, category = "luxury" },
        ["vcogcabrio1"] = { name = "Cognoscenti Cabrio I", brand = "Enus", model = "vcogcabrio1", price = 185522, category = "luxury", image = "vcogcabrio1.webp" },
        ["windsor3"] = { name = "Windsor Custom", brand = "Enus", model = "windsor3", price = 125522, category = "luxury", image = "windsor3.webp" },
    },
    ["emergency"] = {
        ["gbemsbisonstx"] = { name = "EMS Bison STX", brand = "Bravado", model = "gbemsbisonstx", price = 100000, category = "emergency", image = "gbemsbisonstx.webp" },
        ["gbemsesperta"] = { name = "EMS Esperta", brand = "Bravado", model = "gbemsesperta", price = 100000, category = "emergency", image = "gbemsesperta.webp" },
        ["gbfirevoyager"] = { name = "Fire Voyager", brand = "MTL", model = "gbfirevoyager", price = 100000, category = "emergency", image = "gbfirevoyager.webp" },
        ["gbpolbisonhf"] = { name = "Police Bison HF (2024)", brand = "Bravado", model = "gbpolbisonhf", price = 100000, category = "emergency", image = "gbpolbisonhf.webp" },
        ["gbpolbisonstx"] = { name = "Police Bison STX (2023)", brand = "Bravado", model = "gbpolbisonstx", price = 100000, category = "emergency", image = "gbpolbisonstx.webp" },
        ["gbpolcometcl"] = { name = "Police Comet CL", brand = "Pfister", model = "gbpolcometcl", price = 100000, category = "emergency", image = "gbpolcometcl.webp" },
        ["gbpolcomets2r"] = { name = "Police Comet S2R", brand = "Pfister", model = "gbpolcomets2r", price = 100000, category = "emergency", image = "gbpolcomets2r.webp" },
        ["gbpoldomgsx"] = { name = "Police Dominator GSX", brand = "Vapid", model = "gbpoldomgsx", price = 100000, category = "emergency", image = "gbpoldominatorgsx.webp" },
        ["gbpolprospero"] = { name = "Police Prospero", brand = "Pegassi", model = "gbpolprospero", price = 100000, category = "emergency", image = "gbpolprospero.webp" },
        ["gbpolsolace"] = { name = "Police Solace", brand = "Dewbauchee", model = "gbpolsolace", price = 100000, category = "emergency", image = "gbpolsolace.webp" },
        ["gbpolstanierle"] = { name = "Police Stanier LE", brand = "Vapid", model = "gbpolstanierle", price = 100000, category = "emergency", image = "gbpolstanierle.webp" },
        ["gbpolstarlight"] = { name = "Police Starlight", brand = "Vulcar", model = "gbpolstarlight", price = 100000, category = "emergency", image = "gbpolstarlight.webp" },
        ["gbpolsultanrsx"] = { name = "Police Sultan RSx", brand = "Karin", model = "gbpolsultanrsx", price = 100000, category = "emergency", image = "gbpolsultanrsx.webp" },
        ["gbpoltahomagt"] = { name = "Police Tahoma GT", brand = "Declasse", model = "gbpoltahomagt", price = 100000, category = "emergency", image = "gbpoltahomagt.webp" },
        ["gbpoltr3s"] = { name = "Police TR3 S", brand = "Progen", model = "gbpoltr3s", price = 100000, category = "emergency", image = "gbpoltr3s.webp" },
        ["gbpolturismogt"] = { name = "Police Turismo GT", brand = "Grotti", model = "gbpolturismogt", price = 100000, category = "emergency", image = "gbpolturismogt.webp" },
        ["hazard"] = { name = "Sadler Utility (2000)", brand = "Vapid", model = "hazard", price = 62297, category = "emergency", image = "hazard.webp" },
        ["hazard2"] = { name = "Sadler HD Utility (2008)", brand = "Vapid", model = "hazard2", price = 62297, category = "emergency", image = "hazard2.webp" },
        ["onx_polalamo"] = { name = "Alamo 2700LX (2022-2025)", brand = "Declasse", model = "onx_polalamo", price = 71053, category = "emergency", image = "onx_polalamo.webp" },
        ["onx_polaleu"] = { name = "Aleutian (2024-2025)", brand = "Vapid", model = "onx_polaleu", price = 71053, category = "emergency", image = "onx_polaleu.webp" },
        ["onx_polbison"] = { name = "Bison 35XD (2022-2025)", brand = "Bravado", model = "onx_polbison", price = 71053, category = "emergency", image = "onx_polbison.webp" },
        ["onx_polbison2"] = { name = "Bison 45XD (2022-2025)", brand = "Bravado", model = "onx_polbison2", price = 71053, category = "emergency", image = "onx_polbison2.webp" },
        ["onx_polbison3"] = { name = "Bison 45XD Sasquatch (2022-2025)", brand = "Bravado", model = "onx_polbison3", price = 71053, category = "emergency", image = "onx_polbison3.webp" },
        ["onx_polbison4"] = { name = "Bison 25XD (2022-2025)", brand = "Bravado", model = "onx_polbison4", price = 71053, category = "emergency", image = "onx_polbison4.webp" },
        ["onx_polbuff"] = { name = "Buffalo A/C (2015-2023)", brand = "Bravado", model = "onx_polbuff", price = 71053, category = "emergency", image = "onx_polbuff.webp" },
        ["onx_polbuff2"] = { name = "Police Buffalo 2", brand = "Bravado", model = "onx_polbuff2", price = 70000, category = "emergency", image = "onx_polbuff2.webp" },
        ["onx_polbuffhf"] = { name = "Buffalo Hellfire (2015-2023)", brand = "Bravado", model = "onx_polbuffhf", price = 71053, category = "emergency", image = "onx_polbuffhf.webp" },
        ["onx_polcara"] = { name = "Caracara Raid (2017-2020)", brand = "Vapid", model = "onx_polcara", price = 71053, category = "emergency", image = "onx_polcara.webp" },
        ["onx_polcava"] = { name = "Cavalcade XL (2021-2025)", brand = "Albany", model = "onx_polcava", price = 71053, category = "emergency", image = "onx_polcava.webp" },
        ["onx_polcoq"] = { name = "Police Coquette", brand = "Invetero", model = "onx_polcoq", price = 70000, category = "emergency", image = "onx_polcoq.webp" },
        ["onx_polcoq2"] = { name = "Police Coquette 2", brand = "Invetero", model = "onx_polcoq2", price = 70000, category = "emergency", image = "onx_polcoq2.webp" },
        ["onx_polcoq3"] = { name = "Police Coquette 3", brand = "Invetero", model = "onx_polcoq3", price = 70000, category = "emergency", image = "onx_polcoq3.webp" },
        ["onx_poldom"] = { name = "Dominator GT (2018-2023)", brand = "Vapid", model = "onx_poldom", price = 71053, category = "emergency", image = "onx_poldom.webp" },
        ["onx_poldorado"] = { name = "Dorado (1998-2003)", brand = "Bravado", model = "onx_poldorado", price = 71053, category = "emergency", image = "onx_poldorado.webp" },
        ["onx_poldorado2"] = { name = "Dorado AC (2011-2023)", brand = "Bravado", model = "onx_poldorado2", price = 71053, category = "emergency", image = "onx_poldorado2.webp" },
        ["onx_polgaunt"] = { name = "Gauntlet Hellfire (2021-2025)", brand = "Bravado", model = "onx_polgaunt", price = 71053, category = "emergency", image = "onx_polgaunt.webp" },
        ["onx_polgrang"] = { name = "Granger 3600LX (2015-2020)", brand = "Declasse", model = "onx_polgrang", price = 71053, category = "emergency", image = "onx_polgrang.webp" },
        ["onx_polgrang2"] = { name = "Granger 3700LX (2022-2025)", brand = "Declasse", model = "onx_polgrang2", price = 71053, category = "emergency", image = "onx_polgrang2.webp" },
        ["onx_polguard"] = { name = "Police Guardian", brand = "Vapid", model = "onx_polguard", price = 70000, category = "emergency", image = "onx_polguard.webp" },
        ["onx_polguard2"] = { name = "Police Guardian 2", brand = "Vapid", model = "onx_polguard2", price = 70000, category = "emergency", image = "onx_polguard2.webp" },
        ["onx_polguard3"] = { name = "Police Guardian 3", brand = "Vapid", model = "onx_polguard3", price = 70000, category = "emergency", image = "onx_polguard3.webp" },
        ["onx_polguard4"] = { name = "Police Guardian 4", brand = "Vapid", model = "onx_polguard4", price = 70000, category = "emergency", image = "onx_polguard4.webp" },
        ["onx_polinvict"] = { name = "Invictus (2022-2025)", brand = "Canis", model = "onx_polinvict", price = 71053, category = "emergency", image = "onx_polinvict.webp" },
        ["onx_polinvict2"] = { name = "Invictus Overland (2022-2025)", brand = "Canis", model = "onx_polinvict2", price = 71053, category = "emergency", image = "onx_polinvict2.webp" },
        ["onx_polkandra"] = { name = "Kandra (2020-2025)", brand = "Ubermacht", model = "onx_polkandra", price = 71053, category = "emergency", image = "onx_polkandra.webp" },
        ["onx_polmerit"] = { name = "Merit (1991-1996)", brand = "Declasse", model = "onx_polmerit", price = 71053, category = "emergency", image = "onx_polmerit.webp" },
        ["onx_polmerit2"] = { name = "Police Merit 2", brand = "Declasse", model = "onx_polmerit2", price = 70000, category = "emergency", image = "onx_polmerit2.webp" },
        ["onx_polmerit3"] = { name = "Merit Classic (1977-1985)", brand = "Declasse", model = "onx_polmerit3", price = 71053, category = "emergency", image = "onx_polmerit3.webp" },
        ["onx_polmonar"] = { name = "Monarch (1998-2011)", brand = "Vapid", model = "onx_polmonar", price = 71053, category = "emergency", image = "onx_polmonar.webp" },
        ["onx_polregent"] = { name = "Regent (2022-2025)", brand = "Brute", model = "onx_polregent", price = 71053, category = "emergency", image = "onx_polregent.webp" },
        ["onx_polregentxl"] = { name = "Regent XL (2022-2025)", brand = "Brute", model = "onx_polregentxl", price = 71053, category = "emergency", image = "onx_polregentxl.webp" },
        ["onx_polsand"] = { name = "Sandstorm D205 (2022-2025)", brand = "Vapid", model = "onx_polsand", price = 71053, category = "emergency", image = "onx_polsand.webp" },
        ["onx_polsandh"] = { name = "Sandstorm D205 Hellenbach (2022-2025)", brand = "Vapid", model = "onx_polsandh", price = 71053, category = "emergency", image = "onx_polsandh.webp" },
        ["onx_polsandk"] = { name = "Police Sandking", brand = "Vapid", model = "onx_polsandk", price = 70000, category = "emergency", image = "onx_polsandk.webp" },
        ["onx_polsandk2"] = { name = "Police Sandking 2", brand = "Vapid", model = "onx_polsandk2", price = 70000, category = "emergency", image = "onx_polsandk2.webp" },
        ["onx_polsandk3"] = { name = "Police Sandking 3", brand = "Vapid", model = "onx_polsandk3", price = 70000, category = "emergency", image = "onx_polsandk3.webp" },
        ["onx_polsandk4"] = { name = "Police Sandking 4", brand = "Vapid", model = "onx_polsandk4", price = 70000, category = "emergency", image = "onx_polsandk4.webp" },
        ["onx_polsandk6"] = { name = "Police Sandking 6", brand = "Vapid", model = "onx_polsandk6", price = 70000, category = "emergency", image = "onx_polsandk6.webp" },
        ["onx_polsandsc"] = { name = "Sandstorm D205 SWB (2022-2025)", brand = "Vapid", model = "onx_polsandsc", price = 71053, category = "emergency", image = "onx_polsandsc.webp" },
        ["onx_polsandxl"] = { name = "Sandstorm D205 XL (2022-2025)", brand = "Vapid", model = "onx_polsandxl", price = 71053, category = "emergency", image = "onx_polsandxl.webp" },
        ["onx_polscout"] = { name = "Scout (2024-2025)", brand = "Vapid", model = "onx_polscout", price = 71053, category = "emergency", image = "onx_polscout.webp" },
        ["onx_polscout2"] = { name = "Scout Classic (1991-1994)", brand = "Vapid", model = "onx_polscout2", price = 71053, category = "emergency", image = "onx_polscout2.webp" },
        ["onx_polsem"] = { name = "Seminole Frontier (1984-1996)", brand = "Canis", model = "onx_polsem", price = 71053, category = "emergency", image = "onx_polsem.webp" },
        ["onx_polstalk"] = { name = "Landstalker (1984-1996)", brand = "Dundreary", model = "onx_polstalk", price = 71053, category = "emergency", image = "onx_polstalk.webp" },
        ["onx_poltavros"] = { name = "Tavros (2013-2016)", brand = "Vapid", model = "onx_poltavros", price = 71053, category = "emergency", image = "onx_poltavros.webp" },
        ["onx_polterm"] = { name = "Terminus (2022-2025)", brand = "Canis", model = "onx_polterm", price = 71053, category = "emergency", image = "onx_polterm.webp" },
        ["onx_polterm2"] = { name = "Terminus Overland (2022-2025)", brand = "Canis", model = "onx_polterm2", price = 71053, category = "emergency", image = "onx_polterm2.webp" },
        ["onx_poltulip"] = { name = "Tulip M-100 (1978-1983)", brand = "Declasse", model = "onx_poltulip", price = 71053, category = "emergency", image = "onx_poltulip.webp" },
        ["onx_polverus"] = { name = "Verus (2024-2025)", brand = "Canis", model = "onx_polverus", price = 71053, category = "emergency", image = "onx_polverus.webp" },
        ["onx_polvigero"] = { name = "Vigero ZX (2016-2025)", brand = "Declasse", model = "onx_polvigero", price = 71053, category = "emergency", image = "onx_polvigero.webp" },
        ["onx_polvstr"] = { name = "Presidente VSTR (2016-2020)", brand = "Albany", model = "onx_polvstr", price = 71053, category = "emergency", image = "onx_polvstr.webp" },
    },
    ["service"] = {
        ["gbboxboy"] = { name = "Boxboy", brand = "Brute", model = "gbboxboy", price = 50000, category = "service", image = "gbboxboy.webp" },
        ["gbboxboyft"] = { name = "Boxboy FT", brand = "Brute", model = "gbboxboyft", price = 50000, category = "service", image = "gbboxboyft.webp" },
        ["gbvoyager"] = { name = "Voyager", brand = "MTL", model = "gbvoyager", price = 50000, category = "service", image = "gbvoyager.webp" },
        ["gbvoyager2"] = { name = "Voyager 2", brand = "MTL", model = "gbvoyager2", price = 50000, category = "service", image = "gbvoyager2.webp" },
        ["gbvoyagerb"] = { name = "Voyager B", brand = "MTL", model = "gbvoyagerb", price = 50000, category = "service", image = "gbvoyagerb.webp" },
        ["gbvoyagerb2"] = { name = "Voyager B2", brand = "MTL", model = "gbvoyagerb2", price = 50000, category = "service", image = "gbvoyagerb2.webp" },
        ["gbvoyagerg"] = { name = "Voyager G", brand = "MTL", model = "gbvoyagerg", price = 50000, category = "service", image = "gbvoyagerg.webp" },
        ["gbvoyagerh"] = { name = "Voyager H", brand = "MTL", model = "gbvoyagerh", price = 50000, category = "service", image = "gbvoyagerh.webp" },
        ["onx_snowsandk"] = { name = "Snow Sandking", brand = "Vapid", model = "onx_snowsandk", price = 48000, category = "service", image = "onx_snowsandk.webp" },
        ["onx_tfboxson"] = { name = "TF Boxson", brand = "Bravado", model = "onx_tfboxson", price = 35000, category = "service", image = "onx_tfboxson.webp" },
        ["onx_tfboxstorm"] = { name = "TF Boxstorm", brand = "Vapid", model = "onx_tfboxstorm", price = 38000, category = "service", image = "onx_tfboxstorm.webp" },
        ["onx_tftowson"] = { name = "TF Towson", brand = "Bravado", model = "onx_tftowson", price = 33000, category = "service", image = "onx_tftowson.webp" },
        ["onx_tftowstorm"] = { name = "TF Towstorm", brand = "Vapid", model = "onx_tftowstorm", price = 36000, category = "service", image = "onx_tftowstorm.webp" },
        ["vbenson1"] = { name = "Benson Retro", brand = "Vapid", model = "vbenson1", price = 47273, category = "service", image = "vbenson1.webp" },
        ["vmule1"] = { name = "Mule Flatbed", brand = "Maibatsu", model = "vmule1", price = 53203, category = "service", image = "vmule1.webp" },
        ["vmule2"] = { name = "Mule Utility", brand = "Maibatsu", model = "vmule2", price = 44967, category = "service", image = "vmule2.webp" },
        ["vmule3"] = { name = "Mule Dump", brand = "Maibatsu", model = "vmule3", price = 44967, category = "service", image = "vmule3.webp" },
        ["vmule4"] = { name = "Mule Box", brand = "Maibatsu", model = "vmule4", price = 64344, category = "service", image = "vmule4.webp" },
        ["vrumpo2"] = { name = "Rumpo Box", brand = "Bravado", model = "vrumpo2", price = 47273, category = "service", image = "vrumpo2.webp" },
        ["vspeedo1"] = { name = "Speedo Box", brand = "Vapid", model = "vspeedo1", price = 47273, category = "service", image = "vspeedo1.webp" },
        ["vyankee1"] = { name = "Yankee", brand = "Vapid", model = "vyankee1", price = 57365, category = "service", image = "vyankee1.webp" },
        ["vyankee2"] = { name = "Yankee", brand = "Vapid", model = "vyankee2", price = 49690, category = "service", image = "vyankee2.webp" },
        ["vyankee3"] = { name = "Yankee", brand = "Vapid", model = "vyankee3", price = 49690, category = "service", image = "vyankee3.webp" },
    },
}

-- Index every active model first so add-ons cannot replace vanilla entries, even
-- when an administrator later moves a vehicle between shop categories.
local existingModels = {}

for _, categoryVehicles in pairs(Config.Vehicles) do
    if type(categoryVehicles) == 'table' then
        for key, vehicleData in pairs(categoryVehicles) do
            if type(vehicleData) == 'table' then
                existingModels[tostring(vehicleData.model or key):lower()] = true
            end
        end
    end
end

for category, categoryVehicles in pairs(addonVehicles) do
    local activeCategory = Config.Vehicles[category]

    if type(activeCategory) ~= 'table' then
        activeCategory = {}
        Config.Vehicles[category] = activeCategory
    end

    for key, vehicleData in pairs(categoryVehicles) do
        local model = tostring(vehicleData.model or key):lower()

        if model ~= '' and not existingModels[model] and activeCategory[key] == nil then
            vehicleData.brand = type(vehicleData.brand) == 'string' and vehicleData.brand:match('%S') and vehicleData.brand or 'Unknown brand'
            vehicleData.model = model
            vehicleData.category = category
            vehicleData.isAddon = true
            activeCategory[key] = vehicleData
            existingModels[model] = true
        end
    end
end
