-- Semente da missão Elysian Chemical Shipment, exportada do rascunho montado no jogo
-- (lua5.4 dev/export_seed.lua meth_elysian_precursors). Para gravar de volta em missions/:
--   lua5.4 dev/build_seed.lua meth_elysian_precursors

return {
    id = "meth_elysian_precursors",
    name = "Elysian Chemical Shipment",
    description = "Roubar tambores de precursor químico de um galpão em Elysian Island e entregar a um contato.",
    category = "meth",
    difficulty = "medium",
    minPlayers = 2,
    maxPlayers = 6,
    cooldownMinutes = 180,
    timeLimitMinutes = 60,
    gangRequired = true,
    gangMinGrade = 0,
    participantRadius = 60,
    start = {
        type = "phone",
        caller = "Contato",
        text = "Tem um carregamento de químico parado num galpão em Elysian. Quatro tambores. Topa?",
    },
    variables = {
        {
            id = "alarm_active",
            type = "boolean",
            default = "false",
            random = {},
        },
        {
            id = "hack_success",
            type = "boolean",
            default = "false",
            random = {},
        },
        {
            id = "reinforcement_called",
            type = "boolean",
            default = "false",
            random = {},
        },
        {
            id = "shipment",
            type = "string",
            random = { "Composto de Limpeza Industrial", "Solvente Industrial X-9", "Desengraxante Pesado" },
        },
        {
            id = "cargo_batch",
            type = "string",
            random = { "B-04", "C-17", "F-11", "A-32" },
        },
        {
            id = "cargo_storage",
            type = "string",
            random = { "Galpão B", "Galpão C", "Depósito 4" },
        },
        {
            id = "delivery_location",
            type = "string",
            random = {},
        },
    },
    zones = {
        {
            id = "elysian",
            label = "Elysian Island",
            coords = { x = -331.116, y = -2776.41, z = 9.078 },
            radius = 220,
        },
        {
            id = "restricted",
            label = "Galpão (área restrita)",
            coords = { x = -331.116, y = -2776.577, z = 11.966 },
            radius = 22,
        },
    },
    pedGroups = {
        {
            id = "ext_guards",
            label = "Seguranças externos",
            alarmOnHostile = true,
            alarmVar = "alarm_active",
            behavior = "guard",
            hostileOnAlarm = true,
            hostileOnDamage = true,
            hostileOnShot = true,
            hostileZone = "restricted",
            peds = {
                {
                    accuracy = 35,
                    armor = 25,
                    combatAbility = 1,
                    combatRange = 1,
                    coords = { x = -350.54, y = -2765.891, z = 6.042, w = 20 },
                    health = 200,
                    model = "s_m_m_security_01",
                    movement = "scenario",
                    scenario = "WORLD_HUMAN_GUARD_STAND",
                    weapon = "WEAPON_PISTOL",
                },
                {
                    accuracy = 35,
                    armor = 25,
                    combatAbility = 1,
                    combatRange = 1,
                    coords = { x = -343.85, y = -2759.964, z = 6.036, w = 80 },
                    health = 200,
                    model = "s_m_m_security_01",
                    movement = "scenario",
                    scenario = "WORLD_HUMAN_GUARD_STAND",
                    weapon = "WEAPON_PISTOL",
                },
                {
                    accuracy = 35,
                    armor = 25,
                    combatAbility = 1,
                    combatRange = 1,
                    coords = { x = -332.256, y = -2786.333, z = 5.145, w = 60 },
                    health = 200,
                    model = "s_m_m_security_01",
                    movement = "patrol",
                    patrolRadius = 12,
                    scenario = "WORLD_HUMAN_GUARD_STAND",
                    weapon = "WEAPON_SMG",
                },
            },
            shotRadius = 80,
            spawnOnStart = false,
            warnRadius = 15,
            warnText = { "Ei! Área restrita. Dá meia volta.", "Aqui não é lugar de passeio. Vaza." },
        },
        {
            id = "warehouse_guards",
            label = "Seguranças do galpão",
            alarmOnHostile = true,
            alarmVar = "alarm_active",
            behavior = "guard",
            hostileOnAlarm = true,
            hostileOnDamage = true,
            hostileOnShot = true,
            hostileZone = "restricted",
            peds = {
                {
                    accuracy = 35,
                    armor = 25,
                    combatAbility = 1,
                    combatRange = 1,
                    coords = { x = -313.067, y = -2774.422, z = 5, w = 30 },
                    health = 200,
                    model = "g_m_y_mexgoon_01",
                    movement = "scenario",
                    scenario = "WORLD_HUMAN_GUARD_STAND",
                    weapon = "WEAPON_SMG",
                },
                {
                    accuracy = 35,
                    armor = 25,
                    combatAbility = 1,
                    combatRange = 1,
                    coords = { x = -312.822, y = -2785.502, z = 5.001, w = 15 },
                    health = 200,
                    model = "g_m_y_mexgoon_01",
                    movement = "scenario",
                    scenario = "WORLD_HUMAN_GUARD_STAND",
                    weapon = "WEAPON_PUMPSHOTGUN",
                },
                {
                    accuracy = 35,
                    armor = 25,
                    combatAbility = 1,
                    combatRange = 1,
                    coords = { x = -326.221, y = -2785.76, z = 5.207, w = 45 },
                    health = 200,
                    model = "g_m_y_mexgoon_01",
                    movement = "scenario",
                    scenario = "WORLD_HUMAN_SMOKING",
                    weapon = "WEAPON_PISTOL",
                },
            },
            shotRadius = 60,
            spawnOnStart = false,
            warnRadius = 8,
            warnText = { "Quem deixou você entrar?" },
        },
        {
            id = "office_guard",
            label = "Segurança do escritório",
            alarmOnHostile = true,
            alarmVar = "alarm_active",
            behavior = "guard",
            hostileOnAlarm = true,
            hostileOnDamage = true,
            hostileOnShot = true,
            hostileZone = "restricted",
            peds = {
                {
                    accuracy = 35,
                    armor = 25,
                    combatAbility = 1,
                    combatRange = 1,
                    coords = { x = -329.615, y = -2775.135, z = 5.207, w = 290 },
                    health = 200,
                    model = "s_m_m_security_01",
                    movement = "scenario",
                    scenario = "WORLD_HUMAN_CLIPBOARD",
                    weapon = "WEAPON_PISTOL",
                },
            },
            shotRadius = 40,
            spawnOnStart = false,
            warnRadius = 5,
            warnText = { "O escritório tá fechado." },
        },
    },
    vehicles = {
        {
            id = "van",
            label = "Van da carga",
            cargoCapacity = 4,
            coords = { x = 449.029, y = -1960.989, z = 22.919, w = 175 },
            giveKeys = true,
            locked = false,
            model = "speedo",
            required = true,
            spawnOnStart = true,
        },
    },
    props = {},
    cargo = {
        {
            id = "barrels",
            label = "Tambores químicos",
            canSprint = false,
            carryPreset = "barrel",
            correctLabel = "Lote {{cargo_batch}} — {{shipment}}",
            decoyVar = "cargo_batch",
            inspect = true,
            mode = "carry",
            model = "prop_barrel_02a",
            pieces = {
                { x = -327.579, y = -2794.221, z = 4.692, w = 0 },
                { x = -327.099, y = -2793.6, z = 4.692, w = 0 },
                { x = -328.923, y = -2794.363, z = 4.692, w = 0 },
                { x = -329.805, y = -2794.446, z = 4.692, w = 0 },
                { x = -327.247, y = -2791.432, z = 4.692, w = 0 },
                { x = -327.111, y = -2788.888, z = 4.692, w = 0 },
                { x = -327.003, y = -2788.112, z = 4.692, w = 0 },
                { x = -328.878, y = -2785.586, z = 4.692, w = 0 },
            },
            quantity = 4,
            randomizeCorrect = true,
            requireVehicle = true,
            revealed = false,
            vehicleClasses = {},
            vehicleId = "van",
            vehicleMode = "mission",
            vehicleModels = {},
        },
    },
    interactions = {
        {
            id = "office_pc",
            label = "Hackear computador",
            difficulty = 1,
            consumeItem = false,
            coords = { x = -324.897, y = -2772.577, z = 5.283, w = 225 },
            distance = 1.5,
            duration = 6,
            infoLines = {
                {
                    label = "Carga",
                    value = "{{shipment}}",
                },
                {
                    label = "Lote",
                    value = "{{cargo_batch}}",
                },
                {
                    label = "Armazenado",
                    value = "{{cargo_storage}}",
                },
            },
            infoTitle = "MANIFESTO DE CARGA",
            kind = "hack",
            minigame = "ox_lib:skillcheck",
            model = "prop_laptop_01a",
            onFailure = {
                {
                    type = "set_var",
                    value = "true",
                    var = "alarm_active",
                },
                {
                    type = "notify",
                    kind = "warning",
                    text = "O alarme disparou. Deu pra ver o lote antes de travar: {{cargo_batch}}.",
                },
                {
                    type = "reveal_cargo",
                    cargo = "barrels",
                },
            },
            onSuccess = {
                {
                    type = "set_var",
                    value = "true",
                    var = "hack_success",
                },
                {
                    type = "set_var",
                    value = "false",
                    var = "alarm_active",
                },
                {
                    type = "reveal_cargo",
                    cargo = "barrels",
                },
            },
            once = true,
            retry = false,
            revealed = true,
        },
    },
    reinforcements = {
        {
            id = "suv",
            label = "SUV de reforço",
            arrivalDistance = 18,
            crew = {
                {
                    accuracy = 40,
                    armor = 50,
                    combatAbility = 2,
                    combatRange = 1,
                    health = 200,
                    model = "g_m_y_mexgoon_01",
                    weapon = "WEAPON_PISTOL",
                },
                {
                    accuracy = 40,
                    armor = 50,
                    combatAbility = 2,
                    combatRange = 1,
                    health = 200,
                    model = "g_m_y_mexgoon_01",
                    weapon = "WEAPON_SMG",
                },
                {
                    accuracy = 40,
                    armor = 50,
                    combatAbility = 2,
                    combatRange = 1,
                    health = 200,
                    model = "g_m_y_mexgoon_01",
                    weapon = "WEAPON_SMG",
                },
                {
                    accuracy = 40,
                    armor = 50,
                    combatAbility = 2,
                    combatRange = 1,
                    health = 200,
                    model = "g_m_y_mexgoon_01",
                    weapon = "WEAPON_PUMPSHOTGUN",
                },
            },
            destination = { x = -334.393, y = -2764.418, z = 4.001 },
            drivingStyle = "rushed",
            engage = true,
            exitOnArrival = true,
            maxTravelSeconds = 150,
            model = "granger",
            route = {},
            spawn = { x = -341.058, y = -2715.444, z = 5.849, w = 145 },
            speed = 28,
        },
    },
    chases = {
        {
            id = "enemy_suv",
            label = "SUV inimiga",
            countMax = 2,
            countMin = 1,
            crew = {
                {
                    accuracy = 40,
                    armor = 50,
                    combatAbility = 2,
                    combatRange = 1,
                    health = 200,
                    model = "g_m_y_mexgoon_01",
                    weapon = "WEAPON_MICROSMG",
                },
                {
                    accuracy = 40,
                    armor = 50,
                    combatAbility = 2,
                    combatRange = 1,
                    health = 200,
                    model = "g_m_y_mexgoon_01",
                    weapon = "WEAPON_PISTOL",
                },
                {
                    accuracy = 40,
                    armor = 50,
                    combatAbility = 2,
                    combatRange = 1,
                    health = 200,
                    model = "g_m_y_mexgoon_01",
                    weapon = "WEAPON_MICROSMG",
                },
            },
            driverShoots = false,
            drivingStyle = "aggressive",
            durationSeconds = 240,
            loseDistance = 450,
            maxSpawnDistance = 450,
            maxSpeed = 45,
            minSpawnDistance = 120,
            model = "granger",
            passengersShoot = true,
            ram = true,
            spawnMode = "both",
            spawnPoints = {
                { x = 303.547, y = -2502.261, z = 5.338, w = 265 },
                { x = 347.267, y = -2199.778, z = 12.327, w = 330 },
                { x = 255.166, y = -2065.789, z = 16.48, w = 75 },
                { x = 114.071, y = -2026.605, z = 17.261, w = 155 },
            },
            waves = {
                {
                    countMax = 3,
                    countMin = 2,
                    delaySeconds = 20,
                    model = "bati",
                },
            },
        },
    },
    deliveryGroups = {
        {
            id = "meth_dropoffs",
            label = "Pontos de entrega de meth",
            points = {
                {
                    label = "Cypress Flats",
                    coords = { x = 2671.402, y = 3513.115, z = 51.712, w = 5 },
                    npcCoords = { x = 2668.035, y = 3510.014, z = 52.033, w = 350.845 },
                    parkCoords = { x = 2667.591, y = 3518.473, z = 51.712, w = 345 },
                    radius = 20,
                },
            },
        },
    },
    steps = {
        {
            id = "get_van",
            type = "vehicle_enter",
            label = "Pegar a van",
            enabled = true,
            objective = "Pegue a van da carga.",
            onComplete = {},
            onStart = {},
            showGps = true,
            vehicle = "van",
            who = "driver",
        },
        {
            id = "go_elysian",
            type = "goto",
            label = "Ir até Elysian Island",
            blipArea = false,
            blipColor = 5,
            blipLabel = "Galpão de Elysian",
            blipSprite = 473,
            coords = { x = -354.471, y = -2755.642, z = 5.045 },
            enabled = true,
            objective = "Vá até o galpão em Elysian Island.",
            onComplete = {
                {
                    type = "spawn_group",
                    group = "warehouse_guards",
                },
                {
                    type = "spawn_group",
                    group = "office_guard",
                },
                {
                    type = "spawn_group",
                    group = "ext_guards",
                },
            },
            onStart = {},
            radius = 100,
            showBlip = true,
            showGps = true,
            who = "any",
        },
        {
            id = "find_manifest",
            type = "interact",
            label = "Achar o manifesto",
            complete = "any",
            enabled = true,
            interaction = "office_pc",
            objective = "Encontre informações sobre o carregamento.",
            onComplete = {},
            onStart = {},
            showBlip = false,
        },
        {
            id = "load_barrels",
            type = "cargo",
            label = "Carregar a van",
            cargo = "barrels",
            count = 0,
            enabled = true,
            objective = "Carregue os tambores químicos na van.",
            onComplete = {},
            onStart = {},
            reveal = true,
            target = "loaded",
        },
        {
            id = "escape",
            type = "leave_area",
            label = "Sair de Elysian",
            cargo = "barrels",
            cargoCount = 0,
            coords = { x = -202.593, y = -2622.9, z = 5.017 },
            enabled = true,
            objective = "Saia de Elysian Island com a carga.",
            onComplete = {
                {
                    type = "send_sms",
                    text = "Bom trabalho. Tenho um lugar para vocês deixarem isso.",
                },
                {
                    type = "pick_delivery",
                    group = "meth_dropoffs",
                    var = "delivery_location",
                },
                {
                    type = "chance",
                    ["else"] = {},
                    percent = 60,
                    ["then"] = {
                        {
                            type = "wait",
                            seconds = 20,
                            secondsMax = 40,
                        },
                        {
                            type = "start_chase",
                            chase = "enemy_suv",
                        },
                    },
                },
            },
            onStart = {},
            radius = 350,
            showArea = true,
            who = "vehicle",
        },
        {
            id = "deliver",
            type = "deliver",
            label = "Entregar a carga",
            cargo = "barrels",
            blipLabel = "Entrega",
            consume = true,
            driveAwaySeconds = 45,
            enabled = true,
            handoff = true,
            holdSeconds = 3,
            mode = "vehicle",
            npcModel = "g_m_m_chicold_01",
            npcOffset = 4,
            npcText = { "Coloca os tambores atrás. Rápido." },
            objective = "Entregue os tambores em {{delivery_location}}.",
            onComplete = {},
            onStart = {},
            parkRadius = 4,
            required = 0,
            source = "var",
            var = "delivery_location",
        },
    },
    triggers = {
        {
            id = "arrive_area",
            label = "Chegada a Elysian cria os seguranças",
            actions = {
                {
                    type = "spawn_group",
                    group = "ext_guards",
                },
                {
                    type = "spawn_group",
                    group = "warehouse_guards",
                },
                {
                    type = "spawn_group",
                    group = "office_guard",
                },
            },
            chance = 100,
            delay = 0,
            delayMax = 0,
            match = "elysian",
            on = "zone_enter",
            once = true,
        },
        {
            id = "alarm_first_barrel",
            label = "Primeiro tambor com alarme = reforço",
            actions = {
                {
                    type = "set_var",
                    value = "true",
                    var = "reinforcement_called",
                },
                {
                    type = "wait",
                    seconds = 30,
                    secondsMax = 0,
                },
                {
                    type = "send_reinforcement",
                    reinforcement = "suv",
                },
            },
            chance = 100,
            condition = {
                mode = "all",
                rules = {
                    {
                        op = "true",
                        var = "alarm_active",
                    },
                    {
                        op = "false",
                        var = "reinforcement_called",
                    },
                },
            },
            delay = 0,
            delayMax = 0,
            match = "barrels",
            on = "cargo_picked",
            once = false,
        },
        {
            id = "alarm_after_pickup",
            label = "Alarme depois do primeiro tambor = reforço",
            actions = {
                {
                    type = "set_var",
                    value = "true",
                    var = "reinforcement_called",
                },
                {
                    type = "wait",
                    seconds = 30,
                    secondsMax = 0,
                },
                {
                    type = "send_reinforcement",
                    reinforcement = "suv",
                },
            },
            chance = 100,
            condition = {
                mode = "all",
                rules = {
                    {
                        op = "true",
                        var = "alarm_active",
                    },
                    {
                        op = "gte",
                        value = "1",
                        var = "cargo.barrels.picked",
                    },
                    {
                        op = "false",
                        var = "reinforcement_called",
                    },
                },
            },
            delay = 0,
            delayMax = 0,
            match = "alarm_active",
            on = "var_changed",
            once = false,
        },
    },
    rewards = {
        {
            type = "item",
            amount = 2,
            item = "chemical_precursor",
            split = "each",
        },
    },
}
