const WORDS: string[] = [
    'about', 'above', 'abuse', 'actor', 'acute', 'admit', 'adopt', 'adult',
    'after', 'again', 'agent', 'agree', 'ahead', 'alarm', 'album', 'alert',
    'alike', 'alive', 'allow', 'alone', 'along', 'alter', 'angel', 'anger',
    'angle', 'angry', 'apart', 'apple', 'apply', 'arena', 'argue', 'arise',
    'array', 'aside', 'asset', 'audio', 'audit', 'avoid', 'award', 'aware',
    'badly', 'baker', 'bases', 'beach', 'began', 'begin', 'being', 'below',
    'bench', 'birth', 'black', 'blame', 'blank', 'blast', 'blind', 'block',
    'blood', 'board', 'boost', 'booth', 'bound', 'brain', 'brand', 'brave',
    'bread', 'break', 'breed', 'brief', 'bring', 'broad', 'broke', 'brown',
    'brush', 'build', 'built', 'buyer', 'cabin', 'cable', 'candy', 'cargo',
    'carry', 'catch', 'cause', 'chain', 'chair', 'chaos', 'charm', 'chart',
    'chase', 'cheap', 'check', 'chess', 'chest', 'chief', 'child', 'civil',
    'claim', 'class', 'clean', 'clear', 'click', 'cliff', 'climb', 'clock',
    'close', 'cloud', 'coach', 'coast', 'could', 'count', 'court', 'cover',
    'crack', 'craft', 'crash', 'crazy', 'cream', 'crime', 'cross', 'crowd',
    'crown', 'crude', 'curve', 'cycle', 'daily', 'dance', 'dealt', 'death',
    'delay', 'depth', 'doing', 'doubt', 'dozen', 'draft', 'drama', 'drank',
    'dream', 'dress', 'drink', 'drive', 'drove', 'dying', 'eager', 'early',
    'earth', 'eight', 'elite', 'empty', 'enemy', 'enjoy', 'enter', 'entry',
    'equal', 'error', 'event', 'every', 'exact', 'exist', 'extra', 'faith',
    'false', 'fault', 'favor', 'fence', 'fewer', 'fiber', 'field', 'fifth',
    'fifty', 'fight', 'final', 'first', 'fixed', 'flame', 'flash', 'fleet',
    'floor', 'fluid', 'focus', 'force', 'forth', 'forty', 'forum', 'found',
    'frame', 'frank', 'fraud', 'fresh', 'front', 'frost', 'fruit', 'fully',
    'funny', 'ghost', 'giant', 'given', 'glass', 'globe', 'glory', 'grace',
    'grade', 'grain', 'grand', 'grant', 'grass', 'grave', 'great', 'green',
    'gross', 'group', 'grown', 'guard', 'guess', 'guest', 'guide', 'happy',
    'harsh', 'heart', 'heavy', 'hello', 'horse', 'hotel', 'house', 'human',
    'humor', 'hurry', 'ideal', 'image', 'imply', 'index', 'inner', 'input',
    'issue', 'joint', 'judge', 'juice', 'known', 'label', 'labor', 'large',
    'laser', 'later', 'laugh', 'layer', 'learn', 'least', 'leave', 'legal',
    'lemon', 'level', 'light', 'limit', 'lobby', 'local', 'logic', 'loose',
    'lower', 'lucky', 'lunch', 'lyric', 'magic', 'major', 'maker', 'march',
    'match', 'maybe', 'mayor', 'meant', 'medal', 'media', 'metal', 'meter',
    'might', 'minor', 'minus', 'mixed', 'model', 'money', 'month', 'moral',
    'motor', 'mount', 'mouse', 'mouth', 'movie', 'music', 'naked', 'nerve',
    'never', 'newly', 'night', 'noise', 'north', 'noted', 'novel', 'nurse',
    'ocean', 'offer', 'often', 'order', 'other', 'ought', 'paint', 'panel',
    'paper', 'party', 'peace', 'phase', 'phone', 'photo', 'piano', 'piece',
    'pilot', 'pitch', 'place', 'plain', 'plane', 'plant', 'plate', 'point',
    'pound', 'power', 'press', 'price', 'pride', 'prime', 'print', 'prior',
    'prize', 'proof', 'proud', 'prove', 'queen', 'quick', 'quiet', 'quite',
    'radio', 'raise', 'range', 'rapid', 'ratio', 'reach', 'react', 'ready',
    'realm', 'rebel', 'refer', 'relax', 'reply', 'rifle', 'right', 'rigid',
    'rival', 'river', 'robot', 'rough', 'round', 'route', 'royal', 'rural',
    'scale', 'scene', 'scope', 'score', 'sense', 'serve', 'seven', 'shall',
    'shape', 'share', 'sharp', 'sheet', 'shelf', 'shell', 'shift', 'shine',
    'shirt', 'shock', 'shoot', 'short', 'shown', 'sight', 'silly', 'since',
    'sixth', 'sixty', 'sized', 'skill', 'sleep', 'slide', 'small', 'smart',
    'smile', 'smoke', 'snake', 'solar', 'solid', 'solve', 'sorry', 'sound',
    'south', 'space', 'spare', 'speak', 'speed', 'spend', 'spent', 'spice',
    'split', 'spoke', 'sport', 'staff', 'stage', 'stake', 'stand', 'start',
    'state', 'steam', 'steel', 'steep', 'steer', 'stern', 'stick', 'still',
    'stock', 'stone', 'stood', 'store', 'storm', 'story', 'strip', 'stuck',
    'study', 'stuff', 'style', 'sugar', 'suite', 'super', 'sweet', 'swift',
    'swing', 'table', 'taken', 'taste', 'taxes', 'teach', 'thank', 'theft',
    'their', 'theme', 'there', 'these', 'thick', 'thing', 'think', 'third',
    'those', 'three', 'threw', 'throw', 'tiger', 'tight', 'tired', 'title',
    'today', 'token', 'topic', 'total', 'touch', 'tough', 'tower', 'trace',
    'track', 'trade', 'trail', 'train', 'treat', 'trend', 'trial', 'tribe',
    'trick', 'tried', 'truck', 'truly', 'trust', 'truth', 'twice', 'twist',
    'ultra', 'uncle', 'under', 'union', 'unite', 'unity', 'until', 'upper',
    'upset', 'urban', 'usual', 'valid', 'value', 'video', 'virus', 'visit',
    'vital', 'voice', 'waste', 'watch', 'water', 'wheel', 'where', 'which',
    'while', 'white', 'whole', 'whose', 'woman', 'world', 'worry', 'worse',
    'worst', 'worth', 'would', 'wound', 'write', 'wrong', 'wrote', 'yield',
    'young', 'youth',
];

export function randomWord(): string {
    return WORDS[Math.floor(Math.random() * WORDS.length)].toUpperCase();
}

export function wordForGame(gameId: string): string {
    let h = 0;
    for (let i = 0; i < gameId.length; i++) h = (Math.imul(h, 31) + gameId.charCodeAt(i)) >>> 0;
    return WORDS[h % WORDS.length].toUpperCase();
}
